### PR TITLE
Print serviceaccount RBAC after e2e fedora run

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:
This should help us trimming down the required RBAC rules if needed.
#### Which issue(s) this PR fixes:

None
#### Does this PR have test?
None

#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
I think we can keep the script, it's handy :)

**Review by jhrozek — APPROVED** [review]
/lgtm

**Pull request merged**
