### PR TITLE
Bump nixpkgs (and update golang to v1.18.2)

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
This contains the golang version bump to v1.18.2.

#### Which issue(s) this PR fixes:

None
#### Does this PR have test?
None

#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by jhrozek — APPROVED** [review]
/lgtm

**Review by JAORMX — APPROVED** [review]

**Comment by saschagrunert** [comment]
Rebased

**Comment by saschagrunert** [comment]
Hm why does this timeout :thinking:

**Review by JAORMX — APPROVED** [review]
/lgtm

**Comment by saschagrunert** [comment]
Found an issue on container start:

```
vagrant@ubuntu2110:/vagrant$ k logs spod-hzcbz -c security-profiles-operator
runtime/cgo: pthread_create failed: Operation not permitted
SIGABRT: abort
PC=0x171a5cf m=0 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0x171a5cf
stack: frame={sp:0x7ffeeb74ce20, fp:0x0} stack=[0x7ffeeb54e360,0x7ffeeb74d3a0)
0x00007ffeeb74cd20:  0x0000000001c2c0da  0x00000000016ac4bc
0x00007ffeeb74cd30:  0x0000002200000003  0x000000000046ec3e <runtime.callCgoMmap+0x000000000000003e>
0x00007ffeeb74cd40:  0x00007ffeeb74cd48  0x00007ffeeb74cd90
0x00007ffeeb74cd50:  0x00007ffeeb74cdc8  0x00007ffeeb74cd98
0x00007ffeeb74cd60:  0x0000000000404f8f <runtime.mmap.func1+0x000000000000004f>  0x00007f7cb10ec000
0x00007ffeeb74cd70:  0x0000000000001000  0x0000003200000003
0x00007ffeeb74cd80:  0x00000000ffffffff  0x00007f7cb10ec000
0x00007ffeeb74cd90:  0x00007ffeeb74cdd8  0x00007ffeeb74cde8
0x00007ffeeb74cda0:  0x00007ffeeb74cdf8  0x0000000000400000
0x00007ffeeb74cdb0:  0x000000c000000000  0x00007ffeeb74ce08
0x00007ffeeb74cdc0:  0x0000000001787300  0x000000001c000004
0x00007ffeeb74cdd0:  0x00000000017049f0  0x0000000000000000
0x00007ffeeb74cde0:  0x00007f7cc5897733  0x00007ffeeb74d000
0x00007ffeeb74cdf0:  0x0000000000000000  0x0000000000000007
0x00007ffeeb74ce00:  0x00000000044b8df0  0x0000000000000120
0x00007ffeeb74ce10:  0x0000000000000012  0x000000000171a5c1
0x00007ffeeb74ce20: <0x71cef7669037b078  0x00000000044b8e50
0x00007ffeeb74ce30:  0x0000000000000140  0x000000000175571d
0x00007ffeeb74ce40:  0x00007f7c9ec3a640  0x00007ffeeb74d110
0x00007ffeeb74ce50:  0x00007ffeeb74cf6e  0x0000000000000000
0x00007ffeeb74ce60:  0x00007ffeeb74cf6f  0x0000000001718f25
0x00007ffeeb74ce70:  0x000000000042d24d <runtime.(*pageAlloc).update+0x00000000000003ad>  0x00007f7c9ec3a640
0x00007ffeeb74ce80:  0x00000000003d0f00  0x00007f7c9ec3a910
0x00007ffeeb74ce90:  0x00007f7c9ec3a910  0x00007f7c9ec3a910
0x00007ffeeb74cea0:  0x0000000000000000  0x0000000000000006
0x00007ffeeb74ceb0:  0x00007ffeeb74d110  0x0000000001f74d6e
0x00007ffeeb74cec0:  0x00007ffeeb74d1d0  0x0000000001704982
0x00007ffeeb74ced0:  0x00000000044b83c0  0x000000000040122d
0x00007ffeeb74cee0:  0x0000000000000020  0x00007ffeeb74d110
0x00007ffeeb74cef0:  0x00007f7c9ec3a640  0x00007f7c9ea3a000
0x00007ffeeb74cf00:  0x00007f7c9ec3a640  0x00000000017140dd
0x00007ffeeb74cf10:  0x0000000000002031  0x0000000002c10140
runtime: unknown pc 0x171a5cf
stack: frame={sp:0x7ffeeb74ce20, fp:0x0} stack=[0x7ffeeb54e360,0x7ffeeb74d3a0)
0x00007ffeeb74cd20:  0x0000000001c2c0da  0x00000000016ac4bc
0x00007ffeeb74cd30:  0x0000002200000003  0x000000000046ec3e <runtime.callCgoMmap+0x000000000000003e>
0x00007ffeeb74cd40:  0x00007ffeeb74cd48  0x00007ffeeb74cd90
0x00007ffeeb74cd50:  0x00007ffeeb74cdc8  0x00007ffeeb74cd98
0x00007ffeeb74cd60:  0x0000000000404f8f <runtime.mmap.func1+0x000000000000004f>  0x00007f7cb10ec000
0x00007ffeeb74cd70:  0x0000000000001000  0x0000003200000003
0x00007ffeeb74cd80:  0x00000000ffffffff  0x00007f7cb10ec000
0x00007ffeeb74cd90:  0x00007ffeeb74cdd8  0x00007ffeeb74cde8
0x00007ffeeb74cda0:  0x00007ffeeb74cdf8  0x0000000000400000
0x00007ffeeb74cdb0:  0x000000c000000000  0x00007ffeeb74ce08
0x00007ffeeb74cdc0:  0x0000000001787300  0x000000001c000004
0x00007ffeeb74cdd0:  0x00000000017049f0  0x0000000000000000
0x00007ffeeb74cde0:  0x00007f7cc5897733  0x00007ffeeb74d000
0x00007ffeeb74cdf0:  0x0000000000000000  0x0000000000000007
0x00007ffeeb74ce00:  0x00000000044b8df0  0x0000000000000120
0x00007ffeeb74ce10:  0x0000000000000012  0x000000000171a5c1
0x00007ffeeb74ce20: <0x71cef7669037b078  0x00000000044b8e50
0x00007ffeeb74ce30:  0x0000000000000140  0x000000000175571d
0x00007ffeeb74ce40:  0x00007f7c9ec3a640  0x00007ffeeb74d110
0x00007ffeeb74ce50:  0x00007ffeeb74cf6e  0x0000000000000000
0x00007ffeeb74ce60:  0x00007ffeeb74cf6f  0x0000000001718f25
0x00007ffeeb74ce70:  0x000000000042d24d <runtime.(*pageAlloc).update+0x00000000000003ad>  0x00007f7c9ec3a640
0x00007ffeeb74ce80:  0x00000000003d0f00  0x00007f7c9ec3a910
0x00007ffeeb74ce90:  0x00007f7c9ec3a910  0x00007f7c9ec3a910
0x00007ffeeb74cea0:  0x0000000000000000  0x0000000000000006
0x00007ffeeb74ceb0:  0x00007ffeeb74d110  0x0000000001f74d6e
0x00007ffeeb74cec0:  0x00007ffeeb74d1d0  0x0000000001704982
0x00007ffeeb74ced0:  0x00000000044b83c0  0x000000000040122d
0x00007ffeeb74cee0:  0x0000000000000020  0x00007ffeeb74d110
0x00007ffeeb74cef0:  0x00007f7c9ec3a640  0x00007f7c9ea3a000
0x00007ffeeb74cf00:  0x00007f7c9ec3a640  0x00000000017140dd
0x00007ffeeb74cf10:  0x0000000000002031  0x0000000002c10140

goroutine 1 [running]:
runtime.systemstack_switch()
        runtime/asm_amd64.s:436 fp=0xc00005e780 sp=0xc00005e778 pc=0x46ac40
runtime.main()
        runtime/proc.go:170 +0x6d fp=0xc00005e7e0 sp=0xc00005e780 pc=0x43c58d
runtime.goexit()
        runtime/asm_amd64.s:1571 +0x1 fp=0xc00005e7e8 sp=0xc00005e7e0 pc=0x46ce61

rax    0x0
rbx    0x1
rcx    0x171a5cf
rdx    0x6
rdi    0x1
rsi    0x1
rbp    0x7ffeeb74d110
rsp    0x7ffeeb74ce20
r8     0x0
r9     0x0
r10    0x8
r11    0x246
r12    0x1f74d6e
r13    0x6
r14    0x2c93de0
r15    0x7f7c9ed5b15b
rip    0x171a5cf
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
```

**Comment by saschagrunert** [comment]
We would have to allow `clone3` in the seccomp profile I guess.

**Comment by saschagrunert** [comment]
@jhrozek @JAORMX PTAL

**Review by jhrozek — APPROVED** [review]
/lgtm

**Pull request merged**
