### PR TITLE
Use typed bindata for DaemonSet

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
This allows us more type-safe refactorings and reduces some possible
error paths per design.
#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by JAORMX — COMMENTED** [review]
/lgtm

**Comment by JAORMX** [comment]
One reason why I initially submitted this with yaml format as opposed to the straight library-go implementation was that I was hoping that once we upgrade to go 1.16, we could use the new go file embedding and start linting the daemon yaml with a standard kubernetes linter. But I'm not opposed to this change.

**Review by jhrozek — APPROVED** [review]
Looks good, the typed manifest is the same as the previous untyped manifest and basic smoke test succeeded.

**Pull request merged**
