### PR TITLE
Bump version to v0.2.0

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
Update the version to v0.2.0 to prepare the release.
#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
/hold
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by hasheddan — APPROVED** [review]
/lgtm

**Review by pjbgf — APPROVED** [review]
/lgtm

**Review by hasheddan — APPROVED** [review]
/lgtm

**Pull request merged**
