### PR TITLE
make: Set EnableSelinux=true through kustomize for OpenShift

### PR DESCRIPTION
**Pull request by jhrozek**
When deploying on OpenShift, we are typically interested in deploying
the SELinux controller as well. Since we already have a
OpenShift-specific Makefile target that uses a kustomize overlay,
let's just extend that overlay to change the default values of the
'config' ConfigMap.

Closes: #221

/kind cleanup

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Review by JAORMX — APPROVED** [review]

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
