### PR TITLE
Fix bundle goal into the Makefile for macos

### PR DESCRIPTION
**Pull request by ccojocar**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Fix bundle goal into the Makefile for macos.

#### Does this PR introduce a user-facing change?

```release-note
Fix bundle goal into the Makefile for macos.
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]

**Review by JAORMX — APPROVED** [review]

**Comment by ccojocar** [comment]
@saschagrunert @JAORMX now all checks passed. Please could you lgtm this again? Thanks

**Review by saschagrunert — APPROVED** [review]
Awesome, thank you!

**Pull request merged**
