### PR TITLE
Avoid listing pods in the recording webhook handler which leads sometimes to a webhook timeout issue

### PR DESCRIPTION
**Pull request by ccojocar**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Avoid listing pods in the recording webhook handler, because this operation is sometimes really slow leading to a webhook timeout problem.

It seems that listing pods in a cluster with many pods is quite slow, even though the number of pods in the namespace from where they are listed is low. 

This looks like a performance problem in the Kubernetes API server. A list pods API call can take sometime over 30 seconds which is the maximum timeout for a webhook handler in Kubernetes.

The recording webhook doesn't need to list all pods being recorded anyhow in order to maintain the status in the ProfileRecording CR. Every time a Pod is being created/updated or deleted, the webhook handler is called with the Pod object, so it can update the status accordingly.

#### Does this PR have test?

N/A

#### Special notes for your reviewer:p

None

#### Does this PR introduce a user-facing change?

```release-note
NONE

```

### CODE REVIEW

**Comment by ccojocar** [comment]
@saschagrunert Have you managed to fix the vagrant?

**Comment by saschagrunert** [comment]
@ccojocar may I ask you to rebase please?

**Comment by ccojocar** [comment]
I rebased now. Thanks for pining.

**Review by saschagrunert — APPROVED** [review]
Thanks!

**Pull request merged**
