### PR TITLE
Add Affinity to SPOD configuration

### PR DESCRIPTION
**Pull request by ccojocar**
#### What type of PR is this?

/kind api-change 

#### What this PR does / why we need it:

It adds Affinity to the SPOD configuration. 

#### Which issue(s) this PR fixes:

This allows to control the scheduling of spod daemonset pod in a cluster which has nodes with different types of runtimes (e.g. micro-vm, docker, cri-o) which are not tainted but just labeled. 

#### Does this PR introduce a user-facing change?

```release-note
Added Affinity to SPOD configuration.
```

### CODE REVIEW

**Comment by ccojocar** [comment]
The unit tests failure on macos doesn't seem to be related to this change. It looks like a transient failure. The test passed when executed locally on macos.

**Comment by jhrozek** [comment]
> The unit tests failure on macos doesn't seem to be related to this change. It looks like a transient failure. The test passed when executed locally on macos.

Yes, I've seen those, too. I kicked the test now.

**Comment by jhrozek** [comment]
The code looks good, I just wonder if you think this is worth documenting in the `installation-usage.md` document?

**Comment by ccojocar** [comment]
> The code looks good, I just wonder if you think this is worth documenting in the installation-usage.md document?

I can add a note.

**Pull request merged**
