### PR TITLE
enricher: Parse SELinux AVC lines that contain multiple permissions

### LINKED ISSUE #1260: SELinux audit parser fails to parse audit lines with multiple permissions
#### What happened:
My SELinux test recording emitted the following log line:
```
type=AVC msg=audit(1666691794.882:1434): avc:  denied  { read write open } for  pid=94509 comm="aide" path="/hostroot/etc/kubernetes/aide.log.new" dev="nvme0n1p4" ino=167774224 scontext=system_u:system_r:selinuxrecording.process:s0:c218,c875 tcontext=system_u:object_r:kubernetes_file_t:s0 tclass=file permissive=1
```
it did not match the regex at all and wasn't thus parsed

#### What you expected to happen:
the line should be parsed

#### How to reproduce it (as minimally and precisely as possible):
not sure, but putting the above line into the unit tests reproduces the issue 

#### Anything else we need to know?:
N/A

#### Environment:

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): RHCOS 4.11
- Kernel (e.g. `uname -a`): N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by jhrozek**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
This is a valid AVC denial message:
```
type=AVC msg=audit(1666691794.882:1434): avc:  denied  { read write open } for  pid=94509...
```
Note the three permissions inside the curly braces. It did not match the regex at all and wasn't thus parsed.

#### Which issue(s) this PR fixes:
Fixes #1260

#### Does this PR have test?
Only unit tests.

#### Special notes for your reviewer:
I'd love to have a more involved test, but I don't know how. Is it worth moving
some more pieces to a mockable interface just to test this case?

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
Awesome, thank you!

**Review by ccojocar — APPROVED** [review]

**Comment by jhrozek** [comment]
gonna reopen the PR to kick the tests (sorry if this removes lgtm)

**Comment by saschagrunert** [comment]
For ref: https://kubernetes.slack.com/archives/C7J9RP96G/p1667877096344719

**Review by JAORMX — APPROVED** [review]

**Comment by JAORMX** [comment]
/lgtm cancel

let's wait for CI

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
