### PR TITLE
Bump Kubernetes and CRI-O to v1.24.0

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
Update to their latest releases.
#### Which issue(s) this PR fixes:

None
#### Does this PR have test?
None

#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by JAORMX — APPROVED** [review]

**Comment by saschagrunert** [comment]
@jhrozek @JAORMX PTAL

**Review by JAORMX — APPROVED** [review]
/lgtm

**Pull request merged**
