### PR TITLE
Switch to go 1.19

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
Update to the latest golang release.
#### Which issue(s) this PR fixes:

None

#### Does this PR have test?

None

#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
Updated required golang to version 1.19.
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
Requires https://github.com/kubernetes/test-infra/pull/27226

**Comment by saschagrunert** [comment]
@JAORMX @jhrozek @pjbgf PTAL

**Review by jhrozek — APPROVED** [review]
/lgtm

**Review by JAORMX — APPROVED** [review]
/lgtm
/approve
#bleedingedge

**Pull request merged**
