### PR TITLE
Finish profilerecorder unit tests

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
This adds all other required unit test cases and bump the coverage around 98%.
#### Which issue(s) this PR fixes:

None
#### Does this PR have test?
Yes

#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by JAORMX** [comment]
@saschagrunert I'm very much into this extended test coverage!

This is more of a nit and I'll merge this anyway... but could we cover the profilerecorder unit tests with different `t.Run` calls so the documentation would now be a test run name as opposed to a comment? This would make it easier to debug if we would break a test in the future.

**Review by JAORMX — APPROVED** [review]
/lgtm

**Comment by saschagrunert** [comment]
> This is more of a nit and I'll merge this anyway... but could we cover the profilerecorder unit tests with different `t.Run` calls so the documentation would now be a test run name as opposed to a comment? This would make it easier to debug if we would break a test in the future.

Oh yeah, I can follow-up on that :+1:

**Pull request merged**
