### PR TITLE
fix bpf-recorder syscall map out of capacity

### LINKED ISSUE #1111: fail to record deployment pod
#### What happened:
1. deploy a nginx deployment with label=nginx-pod
```
root@ubuntu:~/hml/profilerecording# kubectl get po -n demo -owide
NAME                         READY   STATUS    RESTARTS   AGE   IP             NODE             NOMINATED NODE   READINESS GATES
nginx-pod-5fdc6d77f-8f4bj    1/1     Running   0          10m   10.42.91.209   ubuntu-worker1   <none>           <none>
```
2.create a profilerecording with label=nginx-pod
```
root@ubuntu:~/hml/profilerecording# kubectl get profilerecording -n demo
NAME
my-recording
```
3.delete the pod and generate the seccompProfile
the bpf record logs:
```
Getting syscalls for profile my-recording-nginx-pod-0-1661245432"
I0823 09:09:21.203446  176791 bpfrecorder.go:285] bpf-recorder "msg"="Looking up PID for profile"  "profile"="my-recording-nginx-pod-0-1661245432" "try"=0
E0823 09:09:33.206934  176791 bpfrecorder.go:587] bpf-recorder "msg"="unable to find container ID in cluster, containerID: " "error"="find container ID: wait on retry: timed out waiting for the condition"  "66d965fdeaf367dc3ba340fa2a64401ab93d0f7dee7c1b64af893e694f7ec97f"=null
E0823 09:09:48.997315  176791 bpfrecorder.go:587] bpf-recorder "msg"="unable to find container ID in cluster, containerID: " "error"="find container ID: wait on retry: timed out waiting for the condition"  "66d965fdeaf367dc3ba340fa2a64401ab93d0f7dee7c1b64af893e694f7ec97f"=null
I0823 09:09:48.997370  176791 bpfrecorder.go:308] bpf-recorder "msg"="Got PIDs for the profile: [{id:320478 comm:nginx mntns:4026533007} {id:320491 comm:nginx mntns:4026533007} {id:320492 comm:nginx mntns:4026533007} {id:320493 comm:nginx mntns:4026533007} {id:320494 comm:nginx mntns:4026533007}]"
I0823 09:09:48.998518  176791 bpfrecorder.go:345] bpf-recorder "msg"="Cleaning up BPF hashmaps"
I0823 09:09:49.008765  176791 bpfrecorder.go:257] bpf-recorder "msg"="Not stopping because another recording is in progress"
```
and it did get the seccompProfile.

4.delete the generate pod but no seccompProfile found
bpf recorder logs:
```
Getting syscalls for profile my-recording-nginx-pod-0-1661245752"
I0823 09:16:43.754956  176791 bpfrecorder.go:285] bpf-recorder "msg"="Looking up PID for profile"  "profile"="my-recording-nginx-pod-0-1661245752" "try"=0
I0823 09:17:11.795790  176791 bpfrecorder.go:285] bpf-recorder "msg"="Looking up PID for profile"  "profile"="my-recording-nginx-pod-0-1661245752" "try"=1
```
pod can be deleted, but no seccompProfile found.

#### What you expected to happen:
the second pod can generate the secompProfile as well.

#### How to reproduce it (as minimally and precisely as possible):
the step is above, follow it.

#### Anything else we need to know?:
sometimes it just shows
```
I0823 11:19:01.632117 1100105 bpfrecorder.go:720] bpf-recorder "msg"="Found container ID in cluster"  "containerID"="f65311000e2f2b708e0d57d9199908b9c14884e77e2e5ec4d0cb4def6ba04323" "containerName"="calico-node"
I0823 11:19:01.829289 1100105 bpfrecorder.go:720] bpf-recorder "msg"="Found container ID in cluster"  "containerID"="f65311000e2f2b708e0d57d9199908b9c14884e77e2e5ec4d0cb4def6ba04323" "containerName"="calico-node"
I0823 11:19:02.029860 1100105 bpfrecorder.go:720] bpf-recorder "msg"="Found container ID in cluster"  "containerID"="f65311000e2f2b708e0d57d9199908b9c14884e77e2e5ec4d0cb4def6ba04323" "containerName"="calico-node"
I0823 11:19:02.232930 1100105 bpfrecorder.go:720] bpf-recorder "msg"="Found container ID in cluster"  "containerID"="f65311000e2f2b708e0d57d9199908b9c14884e77e2e5ec4d0cb4def6ba04323" "containerName"="calico-node"
I0823 11:19:02.434099 1100105 bpfrecorder.go:720] bpf-recorder "msg"="Found container ID in cluster"  "containerID"="f65311000e2f2b708e0d57d9199908b9c14884e77e2e5ec4d0cb4def6ba04323" "containerName"="calico-node"
I0823 11:19:02.632431 1100105 bpfrecorder.go:720] bpf-recorder "msg"="Found container ID in cluster"  "containerID"="f65311000e2f2b708e0d57d9199908b9c14884e77e2e5ec4d0cb4def6ba04323" "containerName"="calico-node"
I0823 11:19:02.833428 1100105 bpfrecorder.go:720] bpf-recorder "msg"="Found container ID in cluster"  "containerID"="f65311000e2f2b708e0d57d9199908b9c14884e77e2e5ec4d0cb4def6ba04323" "containerName"="calico-node"
I0823 11:19:03.034221 1100105 bpfrecorder.go:720] bpf-recorder "msg"="Found container ID in cluster"  "containerID"="f65311000e2f2b708e0d57d9199908b9c14884e77e2e5ec4d0cb4def6ba04323" "containerName"="calico-node"
I0823 11:19:03.235105 1100105 bpfrecorder.go:720] bpf-recorder "msg"="Found container ID in cluster"  "containerID"="f65311000e2f2b708e0d57d9199908b9c14884e77e2e5ec4d0cb4def6ba04323" "containerName"="calico-node"
I0823 11:19:03.432070 1100105 bpfrecorder.go:720] bpf-recorder "msg"="Found container ID in cluster"  "containerID"="f65311000e2f2b708e0d57d9199908b9c14884e77e2e5ec4d0cb4def6ba04323" "containerName"="calico-node"
I0823 11:19:03.631014 1100105 bpfrecorder.go:720] bpf-recorder "msg"="Found container ID in cluster"  "containerID"="f65311000e2f2b708e0d57d9199908b9c14884e77e2e5ec4d0cb4def6ba04323" "containerName"="calico-node"
I0823 11:19:03.829859 1100105 bpfrecorder.go:720] bpf-recorder "msg"="Found container ID in cluster"  "containerID"="f65311000e2f2b708e0d57d9199908b9c14884e77e2e5ec4d0cb4def6ba04323" "containerName"="calico-node"
I0823 11:19:04.031463 1100105 bpfrecorder.go:720] bpf-recorder "msg"="Found container ID in cluster"  "containerID"="f65311000e2f2b708e0d57d9199908b9c14884e77e2e5ec4d0cb4def6ba04323" "containerName"="calico-node"
```
and keeps shows and I can't see the useful infomation

#### Environment:

- Cloud provider or hardware configuration: 
-docker rancher v2.5.12
- OS (e.g: `cat /etc/os-release`): NAME
my-recording
root@ubuntu:~/hml/profilerecording# cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
- Kernel (e.g. `uname -a`):
 Linux ubuntu-master 5.11.5-051105-generic #202103091130 SMP Tue Mar 9 11:51:58 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

- Others:

### PR DESCRIPTION
**Pull request by brness**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
fix the issue when the amount of pid reach the maximum capacity of syscallmap, the same pid would come over and over again
#### Does this PR have test?
N/A

#### Special notes for your reviewer:
It may cause the drop of order pid syscall map.
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
@brness thank you for the PR, can you please run `make update-bpf` to re-generate the code?
/ok-to-test

**Comment by brness** [comment]
> *


> @brness thank you for the PR, can you please run `make update-bpf` to re-generate the code? /ok-to-test

Ok, but I'm installing the nix, it may take some time.

**Comment by saschagrunert** [comment]
Thank you! We also require the signed CLA to contribute to this project. :)

**Comment by brness** [comment]
This is my first time to commit a PR, thx for your patience and it feels really good ! XD

**Comment by saschagrunert** [comment]
Please rebase to get the latest CI changes in.

**Comment by brness** [comment]
OK, I already rebase the latest main branch.

**Review by saschagrunert — APPROVED** [review]

**Comment by saschagrunert** [comment]
I'm wondering if we should also increase `MAX_ENTRIES` and re-calculate the max memory usage of the pod.

**Comment by brness** [comment]
> I'm wondering if we should also increase `MAX_ENTRIES` and re-calculate the max memory usage of the container.

I do the test of  increase the size MAX_ENTRIES, but this sometimes would report cannot allocate memory(-12), I'm not sure if the map is too big to create.

**Pull request merged**
