### PR TITLE
Enhance enricher e2e tests

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
Make the enricher based e2e tests more robust and add more test cases.
#### Which issue(s) this PR fixes:

None

#### Does this PR have test?

None

#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
Yay, green tests :green_circle:

**Comment by saschagrunert** [comment]
PTAL @JAORMX @jhrozek

**Review by jhrozek — COMMENTED** [review]
This looks good and I'm always happy about more tests, I just wonder why you opted to not use defer for the cleanup in tests?

**Comment by saschagrunert** [comment]
> This looks good and I'm always happy about more tests, I just wonder why you opted to not use defer for the cleanup in tests?

The main reason was to make them easier to read and understand. Do you prefer re-adding the `defer`s?

**Comment by jhrozek** [comment]
> > This looks good and I'm always happy about more tests, I just wonder why you opted to not use defer for the cleanup in tests?
> 
> The main reason was to make them easier to read and understand. Do you prefer re-adding the `defer`s?

I don't have a strong opinon honestly. I'm going to ack the patch.

**Review by jhrozek — APPROVED** [review]
/lgtm

**Pull request merged**
