### PR TITLE
Rework the bpfrecorder to record syscalls per mntns instead of PID

### LINKED ISSUE #1188: When recording, too many pids are generated in the container and the ebpf map is full
#### What happened:
When recording, too many pids are generated in the container and the ebpf map is full.Mainly because the syscalls map is full, resulting in missing recorded syscalls.This happens when a node records multiple pods at the same time

#### What you expected to happen:
The ebpf map will not be full when recording syscall
#### How to reproduce it (as minimally and precisely as possible):
1.Multi-node k8s cluster 2. profilerecording runs continuously
#### Anything else we need to know?:
1.At present, the mapping relationship of syscall map is that pid corresponds to syscall.
2.In fact, the most reasonable mapping relationship for syscall map should be mntns corresponding to syscall
#### Environment:
K8s version:v1.20.10
OS-IMAGE:Ubuntu 20.04.3 LT
KERNEL-VERSION:5.15.0-46-generic
CONTAINER-RUNTIME:docker://20.10.7
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

### PR DESCRIPTION
**Pull request by ccojocar**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

This pull request reworks and simplifies the bpfrecorder to record the syscalls per mntns instead of PIDs. The mntns is 
unique during the lifecycle of a container while a container can have multiple PIDs.

In addition, now the bpfrecoder associates a security profile defined in the cluster directly with a mntns instead of a PID. 

The `spoc` CLI was adapted to use a mntns instead of a PID when retrieving the syscalls form eBPF map.

Relates to #1213

#### Which issue(s) this PR fixes:

Fixes #1188

#### Does this PR have test?

Yes

#### Does this PR introduce a user-facing change?

```release-note
Reworked the bpfrecorder to record syscalls per mntns intead of PID. 
```

### CODE REVIEW

**Review by saschagrunert — COMMENTED** [review]
Wouldn't this break the `spoc` recording, which relies on the PID rather than the mount namespace?

**Comment by ccojocar** [comment]
> Wouldn't this break the spoc recording, which relies on the PID rather than the mount namespace?

I am checking now the CLI. It'll need maybe to be slightly adapted.

**Comment by ccojocar** [comment]
@saschagrunert I refactored slightly the spoc to use the mnt ns instead of PID when fetching the syscalls from ebpf map. I am still testing since there seems to be an issue when the ebpf program gets loaded.

**Comment by saschagrunert** [comment]
@ccojocar I'm not sure if you're aware of this, but having a bunch of `bpf_printk` debug messages would be probably helpful in general. I think libbpf can also redirect them from `/sys/kernel/debug/tracing/trace_pipe` into the main application somehow. :thinking:

**Comment by ccojocar** [comment]
>  I'm not sure if you're aware of this, but having a bunch of bpf_printk debug messages would be probably helpful in general. I think libbpf-go can also redirect them from /sys/kernel/debug/tracing/trace_pipe into the main application somehow. 🤔

@saschagrunert Thanks, I know about this for runtime debugging. Here the problem is when the program gets loaded, and I haven't figured out what's causing the issue. I am a bit stuck.

```
$sudo ./spoc record -o ./echo.yaml echo
2023/03/02 11:26:50 Loading bpf module
2023/03/02 11:26:50 Using system btf file
libbpf: loading object 'recorder.bpf.o' from buffer
libbpf: elf: section(3) tracepoint/raw_syscalls/sys_enter, size 704, link 0, flags 6, type=1
libbpf: sec 'tracepoint/raw_syscalls/sys_enter': found program 'sys_enter' at insn offset 0 (0 bytes), code size 88 insns (704 bytes)
libbpf: elf: section(4) .reltracepoint/raw_syscalls/sys_enter, size 80, link 13, flags 40, type=9
libbpf: elf: section(5) license, size 13, link 0, flags 3, type=1
libbpf: license of recorder.bpf.o is Dual BSD/GPL
libbpf: elf: section(6) .rodata, size 64, link 0, flags 2, type=1
libbpf: elf: section(7) .maps, size 80, link 0, flags 3, type=1
libbpf: elf: section(8) .BTF, size 66458, link 0, flags 0, type=1
libbpf: elf: section(10) .BTF.ext, size 700, link 0, flags 0, type=1
libbpf: elf: section(13) .symtab, size 312, link 1, flags 0, type=2
libbpf: looking for externs among 13 symbols...
libbpf: collected 0 externs total
libbpf: map 'pid_mntns': at sec_idx 7, offset 0.
libbpf: map 'pid_mntns': found type = 1.
libbpf: map 'pid_mntns': found key [6], sz = 4.
libbpf: map 'pid_mntns': found value [10], sz = 8.
libbpf: map 'pid_mntns': found max_entries = 1.
libbpf: map 'mntns_syscalls': at sec_idx 7, offset 32.
libbpf: map 'mntns_syscalls': found type = 1.
libbpf: map 'mntns_syscalls': found key [10], sz = 8.
libbpf: map 'mntns_syscalls': found value [21], sz = 1024.
libbpf: map 'mntns_syscalls': found max_entries = 8192.
libbpf: map 'events': at sec_idx 7, offset 64.
libbpf: map 'events': found type = 27.
libbpf: map 'events': found max_entries = 16777216.
libbpf: map 'recorder.rodata' (global data): at sec_idx 6, offset 0, flags 480.
libbpf: map 3 is "recorder.rodata"
libbpf: sec '.reltracepoint/raw_syscalls/sys_enter': collecting relocation for section(3) 'tracepoint/raw_syscalls/sys_enter'
libbpf: sec '.reltracepoint/raw_syscalls/sys_enter': relo #0: insn #34 against 'pid_mntns'
libbpf: prog 'sys_enter': found map 0 (pid_mntns, sec 7, off 0) for insn #34
libbpf: sec '.reltracepoint/raw_syscalls/sys_enter': relo #1: insn #53 against 'filter_name'
libbpf: prog 'sys_enter': found data map 3 (recorder.rodata, sec 6, off 0) for insn 53
libbpf: sec '.reltracepoint/raw_syscalls/sys_enter': relo #2: insn #58 against 'filter_name'
libbpf: prog 'sys_enter': found data map 3 (recorder.rodata, sec 6, off 0) for insn 58
libbpf: sec '.reltracepoint/raw_syscalls/sys_enter': relo #3: insn #73 against 'mntns_syscalls'
libbpf: prog 'sys_enter': found map 1 (mntns_syscalls, sec 7, off 32) for insn #73
libbpf: sec '.reltracepoint/raw_syscalls/sys_enter': relo #4: insn #81 against 'events'
libbpf: prog 'sys_enter': found map 2 (events, sec 7, off 64) for insn #81
2023/03/02 11:26:50 Loading bpf object from module
libbpf: map 'pid_mntns': created successfully, fd=7
libbpf: map 'mntns_syscalls': created successfully, fd=8
libbpf: map 'events': created successfully, fd=9
libbpf: map 'recorder.rodata': created successfully, fd=10
libbpf: sec 'tracepoint/raw_syscalls/sys_enter': found 4 CO-RE relocations
libbpf: CO-RE relocating [31] struct trace_event_raw_sys_enter: found target candidate [22068] struct trace_event_raw_sys_enter in [vmlinux]
libbpf: prog 'sys_enter': relo #0: <byte_off> [31] struct trace_event_raw_sys_enter.id (0:1 @ offset 8)
libbpf: prog 'sys_enter': relo #0: matching candidate #0 <byte_off> [22068] struct trace_event_raw_sys_enter.id (0:1 @ offset 8)
libbpf: prog 'sys_enter': relo #0: patched insn #0 (LDX/ST/STX) off 8 -> 8
libbpf: CO-RE relocating [41] struct task_struct: found target candidate [130] struct task_struct in [vmlinux]
libbpf: prog 'sys_enter': relo #1: <byte_off> [41] struct task_struct.nsproxy (0:128 @ offset 3120)
libbpf: prog 'sys_enter': relo #1: matching candidate #0 <byte_off> [130] struct task_struct.nsproxy (0:117 @ offset 2944)
libbpf: prog 'sys_enter': relo #1: patched insn #6 (ALU/ALU64) imm 3120 -> 2944
libbpf: CO-RE relocating [933] struct nsproxy: found target candidate [1640] struct nsproxy in [vmlinux]
libbpf: prog 'sys_enter': relo #2: <byte_off> [933] struct nsproxy.mnt_ns (0:3 @ offset 24)
libbpf: prog 'sys_enter': relo #2: matching candidate #0 <byte_off> [1640] struct nsproxy.mnt_ns (0:3 @ offset 24)
libbpf: prog 'sys_enter': relo #2: patched insn #14 (ALU/ALU64) imm 24 -> 24
libbpf: CO-RE relocating [942] struct mnt_namespace: found target candidate [40177] struct mnt_namespace in [vmlinux]
libbpf: prog 'sys_enter': relo #3: <byte_off> [942] struct mnt_namespace.ns.inum (0:0:2 @ offset 16)
libbpf: prog 'sys_enter': relo #3: matching candidate #0 <byte_off> [40177] struct mnt_namespace.ns.inum (0:0:2 @ offset 16)
libbpf: prog 'sys_enter': relo #3: patched insn #20 (ALU/ALU64) imm 16 -> 16
libbpf: prog 'sys_enter': BPF program load failed: Invalid argument
libbpf: prog 'sys_enter': -- BEGIN PROG LOAD LOG --
R1 type=ctx expected=fp
; u32 syscall_id = args->id;
0: (79) r7 = *(u64 *)(r1 +8)
; u32 syscall_id = args->id;
1: (67) r7 <<= 32
2: (77) r7 >>= 32
; if (syscall_id < 0 || syscall_id >= MAX_SYSCALLS) {
3: (25) if r7 > 0x3ff goto pc+82
 R1=ctx(id=0,
libbpf: prog 'sys_enter': failed to load: -22
libbpf: failed to load object 'recorder.bpf.o'
2023/03/02 11:26:50 Unable to run: run recorder: load: load bpf object: failed to load BPF object: invalid argument
```

The ebpf code doesn't look much different than the one from main branch. 

I suspect is related to my kernel version but the ebpf form main branch loads and executes fine. 

Any idea how I can debug this further, I don't see anything in the kernel log.

**Comment by ccojocar** [comment]
I managed to fix it - `bpftool prog --debug` seems to help and provide more information. 

The `spoc` command works as well with mntns:
```
 sudo ./spoc record -o ./echo.yaml echo
2023/03/02 13:23:29 Loading bpf module
2023/03/02 13:23:29 Using system btf file
libbpf: loading object 'recorder.bpf.o' from buffer
libbpf: elf: section(3) tracepoint/raw_syscalls/sys_enter, size 880, link 0, flags 6, type=1
libbpf: sec 'tracepoint/raw_syscalls/sys_enter': found program 'sys_enter' at insn offset 0 (0 bytes), code size 110 insns (880 bytes)
libbpf: elf: section(4) .reltracepoint/raw_syscalls/sys_enter, size 128, link 13, flags 40, type=9
libbpf: elf: section(5) license, size 13, link 0, flags 3, type=1
libbpf: license of recorder.bpf.o is Dual BSD/GPL
libbpf: elf: section(6) .rodata, size 1088, link 0, flags 2, type=1
libbpf: elf: section(7) .maps, size 80, link 0, flags 3, type=1
libbpf: elf: section(8) .BTF, size 66772, link 0, flags 0, type=1
libbpf: elf: section(10) .BTF.ext, size 844, link 0, flags 0, type=1
libbpf: elf: section(13) .symtab, size 384, link 1, flags 0, type=2
libbpf: looking for externs among 16 symbols...
libbpf: collected 0 externs total
libbpf: map 'pid_mntns': at sec_idx 7, offset 0.
libbpf: map 'pid_mntns': found type = 1.
libbpf: map 'pid_mntns': found key [6], sz = 4.
libbpf: map 'pid_mntns': found value [10], sz = 8.
libbpf: map 'pid_mntns': found max_entries = 1.
libbpf: map 'mntns_syscalls': at sec_idx 7, offset 32.
libbpf: map 'mntns_syscalls': found type = 1.
libbpf: map 'mntns_syscalls': found key [10], sz = 8.
libbpf: map 'mntns_syscalls': found value [21], sz = 1024.
libbpf: map 'mntns_syscalls': found max_entries = 8192.
libbpf: map 'events': at sec_idx 7, offset 64.
libbpf: map 'events': found type = 27.
libbpf: map 'events': found max_entries = 16777216.
libbpf: map 'recorder.rodata' (global data): at sec_idx 6, offset 0, flags 480.
libbpf: map 3 is "recorder.rodata"
libbpf: sec '.reltracepoint/raw_syscalls/sys_enter': collecting relocation for section(3) 'tracepoint/raw_syscalls/sys_enter'
libbpf: sec '.reltracepoint/raw_syscalls/sys_enter': relo #0: insn #35 against 'pid_mntns'
libbpf: prog 'sys_enter': found map 0 (pid_mntns, sec 7, off 0) for insn #35
libbpf: sec '.reltracepoint/raw_syscalls/sys_enter': relo #1: insn #54 against 'filter_name'
libbpf: prog 'sys_enter': found data map 3 (recorder.rodata, sec 6, off 0) for insn 54
libbpf: sec '.reltracepoint/raw_syscalls/sys_enter': relo #2: insn #59 against 'filter_name'
libbpf: prog 'sys_enter': found data map 3 (recorder.rodata, sec 6, off 0) for insn 59
libbpf: sec '.reltracepoint/raw_syscalls/sys_enter': relo #3: insn #74 against 'mntns_syscalls'
libbpf: prog 'sys_enter': found map 1 (mntns_syscalls, sec 7, off 32) for insn #74
libbpf: sec '.reltracepoint/raw_syscalls/sys_enter': relo #4: insn #78 against 'events'
libbpf: prog 'sys_enter': found map 2 (events, sec 7, off 64) for insn #78
libbpf: sec '.reltracepoint/raw_syscalls/sys_enter': relo #5: insn #93 against 'mntns_syscalls'
libbpf: prog 'sys_enter': found map 1 (mntns_syscalls, sec 7, off 32) for insn #93
libbpf: sec '.reltracepoint/raw_syscalls/sys_enter': relo #6: insn #96 against '.rodata'
libbpf: prog 'sys_enter': found data map 3 (recorder.rodata, sec 6, off 0) for insn 96
libbpf: sec '.reltracepoint/raw_syscalls/sys_enter': relo #7: insn #100 against 'mntns_syscalls'
libbpf: prog 'sys_enter': found map 1 (mntns_syscalls, sec 7, off 32) for insn #100
2023/03/02 13:23:29 Loading bpf object from module
libbpf: map 'pid_mntns': created successfully, fd=7
libbpf: map 'mntns_syscalls': created successfully, fd=8
libbpf: map 'events': created successfully, fd=9
libbpf: map 'recorder.rodata': created successfully, fd=10
libbpf: sec 'tracepoint/raw_syscalls/sys_enter': found 4 CO-RE relocations
libbpf: CO-RE relocating [31] struct trace_event_raw_sys_enter: found target candidate [22068] struct trace_event_raw_sys_enter in [vmlinux]
libbpf: prog 'sys_enter': relo #0: <byte_off> [31] struct trace_event_raw_sys_enter.id (0:1 @ offset 8)
libbpf: prog 'sys_enter': relo #0: matching candidate #0 <byte_off> [22068] struct trace_event_raw_sys_enter.id (0:1 @ offset 8)
libbpf: prog 'sys_enter': relo #0: patched insn #0 (LDX/ST/STX) off 8 -> 8
libbpf: CO-RE relocating [41] struct task_struct: found target candidate [130] struct task_struct in [vmlinux]
libbpf: prog 'sys_enter': relo #1: <byte_off> [41] struct task_struct.nsproxy (0:128 @ offset 3120)
libbpf: prog 'sys_enter': relo #1: matching candidate #0 <byte_off> [130] struct task_struct.nsproxy (0:117 @ offset 2944)
libbpf: prog 'sys_enter': relo #1: patched insn #7 (ALU/ALU64) imm 3120 -> 2944
libbpf: CO-RE relocating [933] struct nsproxy: found target candidate [1640] struct nsproxy in [vmlinux]
libbpf: prog 'sys_enter': relo #2: <byte_off> [933] struct nsproxy.mnt_ns (0:3 @ offset 24)
libbpf: prog 'sys_enter': relo #2: matching candidate #0 <byte_off> [1640] struct nsproxy.mnt_ns (0:3 @ offset 24)
libbpf: prog 'sys_enter': relo #2: patched insn #15 (ALU/ALU64) imm 24 -> 24
libbpf: CO-RE relocating [942] struct mnt_namespace: found target candidate [40177] struct mnt_namespace in [vmlinux]
libbpf: prog 'sys_enter': relo #3: <byte_off> [942] struct mnt_namespace.ns.inum (0:0:2 @ offset 16)
libbpf: prog 'sys_enter': relo #3: matching candidate #0 <byte_off> [40177] struct mnt_namespace.ns.inum (0:0:2 @ offset 16)
libbpf: prog 'sys_enter': relo #3: patched insn #21 (ALU/ALU64) imm 16 -> 16
2023/03/02 13:23:29 Getting bpf program sys_enter
2023/03/02 13:23:29 Attaching bpf tracepoint
2023/03/02 13:23:29 Getting syscalls map
2023/03/02 13:23:29 Getting pid_mntns map
2023/03/02 13:23:29 Module successfully loaded
2023/03/02 13:23:29 Running command with PID: 142172

2023/03/02 13:23:29 Processing recorded data
2023/03/02 13:23:29 Found process mntns in bpf map
2023/03/02 13:23:29 Got syscalls: read, write, close, mmap, mprotect, munmap, brk, pread64, access, arch_prctl, futex, set_tid_address, exit_group, openat, newfstatat, set_robust_list, prlimit64, getrandom, rseq
2023/03/02 13:23:29 Wrote seccomp profile to: ./echo.yaml
2023/03/02 13:23:29 Unloading bpf module
```

the result looks like:

```
apiVersion: security-profiles-operator.x-k8s.io/v1beta1
kind: SeccompProfile
metadata:
  creationTimestamp: null
  name: echo
spec:
  architectures:
  - SCMP_ARCH_X86_64
  defaultAction: SCMP_ACT_ERRNO
  syscalls:
  - action: SCMP_ACT_ALLOW
    names:
    - read
    - write
    - close
    - mmap
    - mprotect
    - munmap
    - brk
    - pread64
    - access
    - arch_prctl
    - futex
    - set_tid_address
    - exit_group
    - openat
    - newfstatat
    - set_robust_list
    - prlimit64
    - getrandom
    - rseq
status: {}
```

@saschagrunert I think you can review now my changes. Thanks

**Review by saschagrunert — APPROVED** [review]

**Comment by saschagrunert** [comment]
Awesome work! Thank you!

**Comment by saschagrunert** [comment]
Hm, it looks like that the e2e tests are not happy here, especially with respect to the profile recording / merging.

**Comment by ccojocar** [comment]
Yeah, I am looking into it.

**Comment by ccojocar** [comment]
@saschagrunert I managed to fix the issue. Now all e2e tests passed but the baseprofiles test fails. Not sure what's the reason. I am trying to figure out.

**Comment by saschagrunert** [comment]
@ccojocar yeah it looks like that the seccomp profile will not be reconciled correctly for the test. :thinking:

**Review by saschagrunert — APPROVED** [review]

**Comment by saschagrunert** [comment]
Damn, may I ask you to rebase again?

**Pull request merged**
