### PR TITLE
apparmor recorder: add hugepage support

### PR DESCRIPTION
**Pull request by mhils**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

This PR fixes our AppArmor recorder to detect anonymous huge table usage and work around related AppArmor limitations. This is slightly ugly, but all other workarounds are even more ugly.

#### Which issue(s) this PR fixes:

None

#### Does this PR have test?

Yes

#### Does this PR introduce a user-facing change?

```release-note
Fix AppArmor recording for workloads that use anonymous hugepages.
```

### CODE REVIEW

**Comment by mhils** [comment]
CI is failing because the macOS CI runner does not have `MAP_HUGETLB`. Is macOS a supported build target for SPO?

**Comment by saschagrunert** [comment]
> CI is failing because the macOS CI runner does not have `MAP_HUGETLB`. Is macOS a supported build target for SPO?

I think so, that's why we added the build job. Do you mind fixing the build?

**Comment by mhils** [comment]
Fixed! :)

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
