### PR TITLE
Add cmurphy as a reviewer

### PR DESCRIPTION
**Pull request by cmurphy**
#### What this PR does / why we need it:

This PR adds myself as a reviewer. I've contributed a few features at this point and I think I can help out with reviewing :)

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by cmurphy** [comment]
>   * User is not a member of the org. Satisfy at least one of these conditions to make the user trusted.

I'm not sure what I need to do to fix this.

**Review by saschagrunert — APPROVED** [review]
Yay! 🥳

/lgtm
/ok-to-test

**Comment by saschagrunert** [comment]
/hold 

Saw your comment. Can you please request an org membership in …?

**Comment by cmurphy** [comment]
[**@saschagrunert**](https://github.com/saschagrunert) commented on [Nov 23, 2020, 12:33 PM PST](https://github.com/kubernetes-sigs/security-profiles-operator/pull/161#issuecomment-732410530 "2020-11-23T20:33:22Z - Replied by Github Reply Comments"):
> /hold
> 
> Saw your comment. Can you please request an org membership by opening an issue in: [https://github.com/kubernetes/org/issues/new/choose](https://github.com/kubernetes/org/issues/new/choose)

https://github.com/kubernetes/org/issues/2341

Added you and @hasheddan as sponsors :)

**Comment by saschagrunert** [comment]
> Added you and @hasheddan as sponsors :)

Good, now we just have to wait that someone from the org comes along approving the request :+1:

**Pull request merged**
