### PR TITLE
Bump dependencies

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
This updates the following dependencies:

- github.com/containers/common: v0.26.3 => v0.29.0
- github.com/crossplane/crossplane-runtime: v0.10.0 => v0.11.0
- k8s.io/api: v0.19.3 => v0.19.4
- k8s.io/apimachinery: v0.19.3 => v0.19.4
- sigs.k8s.io/controller-runtime: v0.6.3 => v0.6.4
#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by cmurphy** [comment]
:+1:

**Comment by saschagrunert** [comment]
> 👍

Can you please propose a PR to add yourself as reviewer to the OWNERS of this project? That way you can /lgtm, too.

**Comment by cmurphy** [comment]
[**@saschagrunert**](https://github.com/saschagrunert) commented on [Nov 23, 2020, 11:57 AM PST](https://github.com/kubernetes-sigs/security-profiles-operator/pull/160#issuecomment-732392364 "2020-11-23T19:57:52Z - Replied by Github Reply Comments"):
> > 
> 
> Can you please propose a PR to add yourself as reviewer to the OWNERS of this project? That way you can /lgtm, too.

Sure :)

**Comment by saschagrunert** [comment]
/assign @cmurphy 
I think we can give this a lgtm-try

**Pull request merged**
