### PR TITLE
Add streaming support for enricher metrics

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
This uses the native GRPC streaming feature to increase the metrics
performance.
#### Which issue(s) this PR fixes:

None

#### Does this PR have test?

None

#### Special notes for your reviewer:

None

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
PTAL @JAORMX @jhrozek

**Review by jhrozek — APPROVED** [review]
/lgtm

**Pull request merged**
