### PR TITLE
Fixes getting owner profile: the node status owner is of an unknown kind AppArmorProfile

### PR DESCRIPTION
**Pull request by NahumLitvin**
#### What type of PR is this?

/kind bug

#### Which issue(s) this PR fixes:

Fixes getting owner profile: the node status owner is of an unknown kind #1993

#### Does this PR have test?

N/A.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
@NahumLitvin may I ask you to sign the CLA?

**Comment by NahumLitvin** [comment]
@saschagrunert there is a n ongoing discussion in our internal slack what cla I should sign. cooperate or private 
will sign as soon as someone decides.

**Comment by NahumLitvin** [comment]
@saschagrunert I signed the CLA

**Comment by NahumLitvin** [comment]
I have no idea what fails, can any1 explain?

**Comment by saschagrunert** [comment]
There is still a whitespace change reported by the linter:

```diff
diff --git a/internal/pkg/manager/nodestatus/nodestatus.go b/internal/pkg/manager/nodestatus/nodestatus.go
index 970269e7..84ede56d 100644
--- a/internal/pkg/manager/nodestatus/nodestatus.go
+++ b/internal/pkg/manager/nodestatus/nodestatus.go
@@ -34,7 +34,7 @@ import (
 	"sigs.k8s.io/controller-runtime/pkg/client"
 	"sigs.k8s.io/controller-runtime/pkg/reconcile"
 	"sigs.k8s.io/controller-runtime/pkg/scheme"
-	
+
 	apparmorapi "sigs.k8s.io/security-profiles-operator/api/apparmorprofile/v1alpha1"
 	pbv1alpha1 "sigs.k8s.io/security-profiles-operator/api/profilebase/v1alpha1"
 	seccompprofileapi "sigs.k8s.io/security-profiles-operator/api/seccompprofile/v1beta1"
```

**Comment by NahumLitvin** [comment]
> There is still a whitespace change reported by the linter:
> 
> ```diff
> diff --git a/internal/pkg/manager/nodestatus/nodestatus.go b/internal/pkg/manager/nodestatus/nodestatus.go
> index 970269e7..84ede56d 100644
> --- a/internal/pkg/manager/nodestatus/nodestatus.go
> +++ b/internal/pkg/manager/nodestatus/nodestatus.go
> @@ -34,7 +34,7 @@ import (
>  	"sigs.k8s.io/controller-runtime/pkg/client"
>  	"sigs.k8s.io/controller-runtime/pkg/reconcile"
>  	"sigs.k8s.io/controller-runtime/pkg/scheme"
> -	
> +
>  	apparmorapi "sigs.k8s.io/security-profiles-operator/api/apparmorprofile/v1alpha1"
>  	pbv1alpha1 "sigs.k8s.io/security-profiles-operator/api/profilebase/v1alpha1"
>  	seccompprofileapi "sigs.k8s.io/security-profiles-operator/api/seccompprofile/v1beta1"
> ```

thanks! I dont have the go toolchain on my machine

**Comment by saschagrunert** [comment]
Thanks @NahumLitvin! :pray:

**Comment by NahumLitvin** [comment]
thank you for facilitating my first contribution to oss

**Pull request merged**
