### PR TITLE
Use the PID when looking up the command in eBPF map

### PR DESCRIPTION
**Pull request by ccojocar**
#### Does this PR introduce a user-facing change?

```release-note
Use the PID when looking up the command in eBPF map.
```

### CODE REVIEW

**Comment by pjbgf** [comment]
This is an informal `/lgtm` from me. I think this will make the recording more precise, as it will ignore duplicate command names from other workloads that are not being recorded.

Either way, it would be good to get @saschagrunert :eyes: on it, as he's been closer to the eBPF recording feature.

**Comment by saschagrunert** [comment]
@ccojocar may I ask you to rebase this one again?

**Comment by ccojocar** [comment]
@saschagrunert I rebased. Thanks for looking at this.

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
