### PR TITLE
Do not include YEAR in generated boilerplate

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:
We do not have to include the YEAR in the boilerplate header. This means
we can use a custom header for generated golang code, which should not
change next year.

#### Which issue(s) this PR fixes:

None
#### Does this PR have test?

None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by hasheddan — APPROVED** [review]
/lgtm

**Comment by cmurphy** [comment]
Shouldn't [this file](https://github.com/kubernetes-sigs/security-profiles-operator/blob/master/hack/boilerplate/boilerplate.go.txt) be removed/changed too?

Why is the copyright year not required anymore?

**Comment by saschagrunert** [comment]
> Shouldn't [this file](https://github.com/kubernetes-sigs/security-profiles-operator/blob/master/hack/boilerplate/boilerplate.go.txt) be removed/changed too?

Nope, we still wanna preserve the YEAR for manually edited files.

> Why is the copyright year not required anymore?

Right now the verify boilerplate script skips generated files:
https://github.com/kubernetes/repo-infra/blob/5597dcdfb69ef4f4c7d994c2176034b9d6aa4721/hack/verify_boilerplate.py#L116

I think we should fix that somehow that the script only skips the YEAR instead of skipping the whole test.

**Pull request merged**
