### PR TITLE
Reuse existing bpf code

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
We can eliminate code duplication by reusing the existing BPF recorder in the CLI.

#### Which issue(s) this PR fixes:

Part of #1482 
#### Does this PR have test?

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
@kubernetes-sigs/security-profiles-operator-maintainers PTAL

Ubuntu tests are broken due to Google Cloud issues for now.

**Review by JAORMX — APPROVED** [review]
Thanks for the cleanup!

Can should we wait for the Ubuntu tests to work again before merging this? Or have you tested locally and this could merge as-is?

**Comment by saschagrunert** [comment]
The ubuntu tests should be unrelated (not affected) by this change since we have no CLI e2e testing in place yet.

**Comment by saschagrunert** [comment]
@kubernetes-sigs/security-profiles-operator-maintainers PTAL

**Review by ccojocar — APPROVED** [review]

**Pull request merged**
