### PR TITLE
Fix apparmor profile to work with COS Linux used by GKE

### LINKED ISSUE #2462: AppArmor Profile Loading on GKE COS failed with "open /proc/1/sched: no such file or directory"
#### What happened:
I was installing SPO and trying the AppArmor support on a GKE cluster with COS(Container-Optimized OS) nodes.
I applied the profile with 
`kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/security-profiles-operator/refs/heads/main/examples/apparmorprofile.yaml`

It failed with 
`E0924 21:11:54.292028   17496 apparmorprofile.go:116] "node \"gke-apparmor3-default-pool-1d3cb74c-fr7d\" does not support apparmor" err="profile not added" logger="apparmor-spod" apparmorprofile="test-profile" namespace="default"`
And there is an error message at first
`E0924 21:11:53.983973   17496 apparmorprofile.go:292] "mounting host" err="identifying pid namespace: open /proc/1/sched: no such file or directory" logger="apparmor-spod"`
And I checked on the node, the file doesn't exist.

#### What you expected to happen:
The profile should be installed

#### How to reproduce it (as minimally and precisely as possible):
On a GKE COS cluster, install SPO.
`kubectl -n security-profiles-operator patch spod spod --type=merge -p '{"spec":{"enableAppArmor":true}}'`
`kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/security-profiles-operator/refs/heads/main/examples/apparmorprofile.yaml`
Check the logs of the daemonset.

#### Anything else we need to know?:
I think it is similar to https://github.com/freeipa/freeipa/pull/6453 and related to https://github.com/systemd/systemd/issues/8153

#### Environment:

- Cloud provider or hardware configuration: GCP,
- OS (e.g: `cat /etc/os-release`): "Container-Optimized OS"  VERSION_ID=109  BUILD_ID=17800.309.13
- Kernel (e.g. `uname -a`): Linux gke-apparmor2-default-pool-1a912e31-hlt3 6.1.100+ #1 SMP PREEMPT_DYNAMIC Sat Aug 10 14:21:56 UTC 2024 x86_64 Intel(R) Xeon(R) CPU @ 2.20GHz GenuineIntel GNU/Linux
- Others:

### PR DESCRIPTION
**Pull request by ccojocar**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

These are a number of fixes required in order to get working the apparmor profile recording and installation with COS Linux used by GKE.

The fixes include:
- Update the options of go-apparmor package to assume that the container runs into the host pid namespace. Without this, the go-apparmor package
will try to auto-detect if a container runs into the host namespace but this will require the Linux kernel to be built with CONFIG_SCHED_DEBUG.
This is not the case for COS Linux used by the GKE. This check is not required in a Kubernetes environment since typically the containers run
into the Host PID namespace. For more details see the fix in https://github.com/pjbgf/go-apparmor/pull/30.
- Filter out the invalid file paths such as ` (deleted)` returned by the Linux kernel. These should not land into the apparmor profile.

#### Which issue(s) this PR fixes:

fixes #2462

#### Does this PR introduce a user-facing change?

```release-note
NONE

```

### CODE REVIEW

**Comment by ccojocar** [comment]
@saschagrunert I fixed also the vagrant issue in this pull request.

**Comment by saschagrunert** [comment]
> @saschagrunert I fixed also the vagrant issue in this pull request.

That's awesome, thank you!

**Review by saschagrunert — APPROVED** [review]

**Comment by saschagrunert** [comment]
@ccojocar we have to update runc/crun in CI, but I can follow-up on that in https://github.com/kubernetes-sigs/security-profiles-operator/pull/2535

**Comment by ccojocar** [comment]
> we have to update runc/crun in CI, but I can follow-up on that in https://github.com/kubernetes-sigs/security-profiles-operator/pull/2535

I just bumped the versions in the examples to get the test passing. Should I merge your branch into this?

**Comment by saschagrunert** [comment]
> > we have to update runc/crun in CI, but I can follow-up on that in #2535
> 
> I just bumped the versions in the examples to get the test passing. Should I merge your branch into this?

Yes this would work as well.

**Comment by ccojocar** [comment]
> Yes this would work as well.

I merged your branch. Hopefully now it will pass.

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
