### PR TITLE
Install the default log enricher profile only when log enricher is enabled

### PR DESCRIPTION
**Pull request by ccojocar**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Install the default log enricher seccomp profile only when log enricher is enabled in the spod configuration.

#### Does this PR introduce a user-facing change?

```release-note
Install the default log enricher sccomp profile only when log enricher is enabled in the spod configuration.

```

### CODE REVIEW

**Review by JAORMX — COMMENTED** [review]
LGTM, I'll wait for CI to pass before merging. Thanks!

**Comment by ccojocar** [comment]
Thanks @JAORMX ! It seems that all the tests passed. Please could you have a look over this, and approve it if everything is fine.

**Pull request merged**
