### PR TITLE
Add `release-note-none` label to dependabot updates

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
This saves one more comment before merging those PRs.

#### Which issue(s) this PR fixes:

None
#### Does this PR have test?
None

#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by jhrozek — APPROVED** [review]
/lgtm
the e2e test is surely unrelated, but I'm going to see why it failed anyway

**Comment by saschagrunert** [comment]
> the e2e test is surely unrelated, but I'm going to see why it failed anyway

Not sure if that's the fix but let's give https://github.com/kubernetes-sigs/security-profiles-operator/pull/379 a try.

**Comment by jhrozek** [comment]
> > the e2e test is surely unrelated, but I'm going to see why it failed anyway
> 
> Not sure if that's the fix but let's give #379 a try.

I'm not sure if that would help, because the profile itself is marked as installed so all the nodes /should/ (unless we still have a race) be reconciled at that point. But it's a good PR on its own. What I'm going to submit is to dump the node states to make sure we still don't have a race there. I also wonder if the files are always fsync-ed to the disk, gotta look at how does go's stdlib work..

**Comment by saschagrunert** [comment]
> > > the e2e test is surely unrelated, but I'm going to see why it failed anyway
> > 
> > 
> > Not sure if that's the fix but let's give #379 a try.
> 
> I'm not sure if that would help, because the profile itself is marked as installed so all the nodes /should/ (unless we still have a race) be reconciled at that point. But it's a good PR on its own. What I'm going to submit is to dump the node states to make sure we still don't have a race there. I also wonder if the files are always fsync-ed to the disk, gotta look at how does go's stdlib work..

Sounds good, thank you!

**Pull request merged**
