### PR TITLE
Add log-enricher e2e test

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
Adding a first e2e test for the log enricher feature.
#### Which issue(s) this PR fixes:

None
#### Does this PR have test?
Yes

#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by JAORMX** [comment]
So far so good! Enabling it and this not breaking is a good step :D What else do you plan to test?

**Comment by saschagrunert** [comment]
> So far so good! Enabling it and this not breaking is a good step :D What else do you plan to test?

I have to check if we wan emit a seccomp log to `/dev/kmsg` and will enhance the test case around that :grin:

**Comment by saschagrunert** [comment]
Requires https://github.com/kubernetes-sigs/security-profiles-operator/pull/491

**Comment by saschagrunert** [comment]
Test seems to work :tada: 
```
I0621 15:38:25.417893   46527 enricher.go:99] log-enricher "msg"="audit"  "container"="enrichercontainer" "executable"="/usr/sbin/nginx" "namespace"="default" "node"="127.0.0.1" "pid"=47276 "pod"="enricherpod" "syscallID"=50 "syscallName"="listen" "timestamp"="1624289904.762:9277" "type"="seccomp"
I0621 15:38:25.439005   46527 enricher.go:99] log-enricher "msg"="audit"  "container"="enrichercontainer" "executable"="/usr/sbin/nginx" "namespace"="default" "node"="127.0.0.1" "pid"=47276 "pod"="enricherpod" "syscallID"=50 "syscallName"="listen" "timestamp"="1624289904.762:9278" "type"="seccomp"
I0621 15:38:25.515222   46527 enricher.go:99] log-enricher "msg"="audit"  "container"="enrichercontainer" "executable"="/usr/sbin/nginx" "namespace"="default" "node"="127.0.0.1" "pid"=47276 "pod"="enricherpod" "syscallID"=50 "syscallName"="listen" "timestamp"="1624289904.762:9279" "type"="seccomp"
I0621 15:38:25.631251   46527 enricher.go:99] log-enricher "msg"="audit"  "container"="enrichercontainer" "executable"="/usr/sbin/nginx" "namespace"="default" "node"="127.0.0.1" "pid"=47276 "pod"="enricherpod" "syscallID"=50 "syscallName"="listen" "timestamp"="1624289904.762:9280" "type"="seccomp"
pod "enricherpod" deleted
```

**Comment by saschagrunert** [comment]
Green tests, PTAL @JAORMX @jhrozek

**Review by JAORMX — APPROVED** [review]
/lgtm

nice!

**Pull request merged**
