### PR TITLE
Switch from ring to performance buffer

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
To support older kernels we now use the performance buffer ebpf type rather than the ring buffer.

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes-sigs/security-profiles-operator/issues/795
#### Does this PR have test?

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
Using the ebpf performance buffer type rather than the ring buffer to support older Linux kernel versions.
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
Hm, now I'm getting the invalid argument error here :thinking:

**Review by JAORMX — APPROVED** [review]

**Review by JAORMX — CHANGES_REQUESTED** [review]
uhm...

**Comment by JAORMX** [comment]
> Hm, now I'm getting the invalid argument error here 🤔

in which logs is that?

**Comment by saschagrunert** [comment]
> > Hm, now I'm getting the invalid argument error here thinking
> 
> in which logs is that?

In the e2e tests, I'm also not able to run the ebpf program locally.

**Comment by saschagrunert** [comment]
I'm not sure this feels like a downgrade to me. The fact that older kernel versions do not support the ringbuffer is something we may auto-fix in the future if those systems switch to newer kernels.

**Pull request closed without merging**
