### PR TITLE
Configure Dependabot to also update docker tags

### PR DESCRIPTION
**Pull request by JAORMX**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

This ensures that we get some automation for bumping docker tags.

Automation makes @JAORMX happy.

#### Which issue(s) this PR fixes:

None

#### Does this PR have test?

N/A.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]

**Comment by pjbgf** [comment]
Would this also update the other `Dockerfile` files, that have suffixes?

**Comment by JAORMX** [comment]
@pjbgf I think so... https://github.com/dependabot/dependabot-core/blob/main/docker/lib/dependabot/docker/file_fetcher.rb#L10

**Review by pjbgf — APPROVED** [review]
/lgtm

**Comment by saschagrunert** [comment]
Please rebase to get the latest CI changes in.

**Comment by JAORMX** [comment]
@saschagrunert done

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
