### PR TITLE
Limit log enricher ttl cache size

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
Limiting the cache sizes to not overflow the memory.
#### Which issue(s) this PR fixes:

None
#### Does this PR have test?
None

#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by jhrozek — APPROVED** [review]
/lgtm

**Comment by saschagrunert** [comment]
Tide seems to have trouble with merging this PR…

**Comment by saschagrunert** [comment]
@pjbgf I think this requires GitHub approval now.

**Comment by pjbgf** [comment]
> Tide seems to have trouble with merging this PR…

Yes, we need to "github approve" as well as "/lgtm"

**Review by pjbgf — APPROVED** [review]

**Pull request merged**
