### PR TITLE
Bump to v0.5.0

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:
Refers to #1144 
#### Which issue(s) this PR fixes:

None
#### Does this PR have test?
None

#### Special notes for your reviewer:
PTAL @jhrozek @JAORMX @pjbgf 
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
We can wait for https://github.com/kubernetes-sigs/security-profiles-operator/pull/1235

/hold

**Comment by jhrozek** [comment]
We seem to be having issues pulling images, with some additional debugging I see:
```
NAME                                          READY   STATUS             RESTARTS   AGE
security-profiles-operator-76d4498fbf-7x5sc   0/1     ImagePullBackOff   0          2m15s
security-profiles-operator-76d4498fbf-bkwjb   0/1     ImagePullBackOff   0          2m15s
security-profiles-operator-76d4498fbf-f845w   0/1     ImagePullBackOff   0          2m15s
```
...looking intensifies..

**Comment by saschagrunert** [comment]
> We seem to be having issues pulling images, with some additional debugging I see:

Is the image the localhost/ one? :thinking:

**Comment by jhrozek** [comment]
No, it seems the deployment refers to the unreleased image:
```
2022-10-17T11:37:05.1515988Z     Image:      k8s.gcr.io/security-profiles-operator/security-profiles-operator:v0.5.0
```

**Comment by saschagrunert** [comment]
@jhrozek so the image seems to come out of the catalog container. Do you have any clue how we can fix that in the CI?

**Comment by jhrozek** [comment]
> @jhrozek so the image seems to come out of the catalog container. Do you have any clue how we can fix that in the CI?

So in the OLM script we make a deployment that should reference the local image with:
```
    OPERATOR_MANIFEST=deploy/operator-ci.yaml
    # Create a manifest with local image                                                                                                                                                                                                      
    pushd deploy/base                                                                                                                                                                                                                         
    kustomize edit set image security-profiles-operator=$IMG                                                                                                                                                                                  
    popd                                                                                                                                                                                                                                      
    kustomize build --reorder=none deploy/overlays/cluster -o ${OPERATOR_MANIFEST}  
```
but the result still references the gcr image:
```
grep -C3 image\: deploy/operator-ci.yaml
          spec:
            description: ProfileBindingSpec defines the desired state of ProfileBinding.
            properties:
              image:
                description: Image name within pod containers to match to the profile.
                type: string
              profileRef:
--
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: k8s.gcr.io/security-profiles-operator/security-profiles-operator:v0.5.0
        imagePullPolicy: Always
        name: security-profiles-operator
        resources:
```
I think the bug is here, but I don't see it right now

**Comment by saschagrunert** [comment]
/unhold

PTAL @jhrozek @JAORMX @pjbgf

**Review by jhrozek — APPROVED** [review]
/lgtm
yay!

**Review by JAORMX — APPROVED** [review]

**Pull request merged**
