### PR TITLE
Disable e2e tests for now

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind failing-test

#### What this PR does / why we need it:
Disable the vagrant based e2e tests until
https://github.com/actions/runner-images/issues/8730 is resolved.

#### Which issue(s) this PR fixes:

None
#### Does this PR have test?
None

#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
@kubernetes-sigs/security-profiles-operator-maintainers PTAL

**Review by ccojocar — APPROVED** [review]

**Review by ccojocar — APPROVED** [review]

**Pull request merged**
