### PR TITLE
Create an AppArmor profile for the operator

### LINKED ISSUE #65: Create AppArmor profile for the operator
#### What would you like to be added:
A tailor-made AppArmor profile to restrict functionality to the minimum required for the operator to run.

#### Why is this needed:
Better define the attack surface, giving users a clear view of what the operator can/cannot do.

/area security
/priority important-longterm

### PR DESCRIPTION
**Pull request by pjbgf**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
Limits the execution powers of the operator, decreasing its attack surface.

#### Which issue(s) this PR fixes:

Fixes #65 

#### Special notes for your reviewer:

This is an initial profile, however this blocked by https://github.com/kubernetes/kubernetes/issues/97273.

#### Does this PR introduce a user-facing change?

```release-note

```

/hold

### CODE REVIEW

**Comment by pjbgf** [comment]
We may need to try to find a different approach for deploying the operator's own profiles. 
Given that the break-out of a single operator into separate deploy-able components may be a good opportunity to review this.

**Comment by pjbgf** [comment]
@saschagrunert what are your thoughts on this one? Shall we just leave it here until at least https://github.com/kubernetes/kubernetes/pull/97966 is merged?

**Comment by saschagrunert** [comment]
> @saschagrunert what are your thoughts on this one? Shall we just leave it here until at least [kubernetes/kubernetes#97966](https://github.com/kubernetes/kubernetes/pull/97966) is merged?

I assume it does not have any bad implications for older Kubernetes versions, right? If so, then I'd propose we move forward, rebase and get this in :)

**Comment by pjbgf** [comment]
> I assume it does not have any bad implications for older Kubernetes versions, right? If so, then I'd propose we move forward, rebase and get this in :)

@saschagrunert I don't think there would be. But given that the upstream issue is a bit stuck, I will close this issue and may reopen it once we are in a better position.

**Pull request closed without merging**
