### PR TITLE
Update the kubelet volume mount of non-root enabler container on the real object not on a copy of it

### PR DESCRIPTION
**Pull request by ccojocar**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Update the volume mount on the effective object of non-root-enabler container instead of a copy with no effect.

#### Does this PR introduce a user-facing change?

```release-note
Update the volume mount on the effective object of non-root-enabler container instead of a copy with no effect.
```

### CODE REVIEW

**Comment by ccojocar** [comment]
@saschagrunert gocritic seems to hang due to upgrade to Go 1.20: 
```
wrapperFunc yodaStyleExpr]"
level=debug msg="[gocritic] Final used checks (105): [appendAssign appendCombine argOrder assignOp badCall badCond badLock badRegexp badSorting boolExprSimplify builtinShadow builtinShadowDecl captLocal caseOrder codegenComment commentFormatting commentedOutCode commentedOutImport defaultCaseOrder deferInLoop deferUnlambda deprecatedComment docStub dupArg dupBranchBody dupCase dupImport dupSubExpr dynamicFmtString elseif emptyDecl emptyFallthrough emptyStringTest equalFold evalOrder exitAfterDefer exposedSyncMutex externalErrorReassign filepathJoin flagDeref flagName hexLiteral httpNoBody hugeParam ifElseChain importShadow indexAlloc initClause ioutilDeprecated mapKey methodExprCall nestingReduce newDeref nilValReturn octalLiteral offBy1 paramTypeCombine preferDecodeRune preferFilepathJoin preferFprint preferStringWriter preferWriteByte ptrToRefParam rangeExprCopy rangeValCopy redundantSprint regexpMust regexpPattern regexpSimplify returnAfterHttpError ruleguard singleCaseSwitch sliceClear sloppyLen sloppyReassign sloppyTypeAssert sortSlice sprintfQuotedString sqlQuery stringConcatSimplify stringXbytes stringsCompare switchTrue syncMapLoadAndDelete timeCmpSimplify timeExprSimplify todoCommentWithoutDetail tooManyResultsChecker truncateCmp typeAssertChain typeDefFirst typeSwitchVar typeUnparen underef unlabelStmt unlambda unnamedResult unnecessaryBlock unnecessaryDefer unslice valSwap weakCond whyNoLint wrapperFunc yodaStyleExpr]"
level=debug msg="[gocritic] All checks are enabled"
Killed
make: *** [Makefile:359: verify-go-lint] Error 137
```

It is reproducible locally when running the verify with Go 1.20.

**Review by saschagrunert — APPROVED** [review]

**Comment by saschagrunert** [comment]
We have to wait for a new release of golangci-lint, but I expect to happen that sooner than later.

**Comment by ccojocar** [comment]
> We have to wait for a new release of golangci-lint, but I expect to happen that sooner than later.

ok, this means the pull requests are blocked until a new release of golangci-lint is available?

**Comment by saschagrunert** [comment]
No, I think we can
/override pull-security-profiles-operator-verify

**Comment by ccojocar** [comment]
@saschagrunert There was a version yesterday released. I updated in this pull request https://github.com/kubernetes-sigs/security-profiles-operator/pull/1453

**Comment by saschagrunert** [comment]
@ccojocar /retest does not work for GitHub actions, we have to manually re-trigger them.

**Comment by ccojocar** [comment]
> /retest does not work for GitHub actions, we have to manually re-trigger them.

@saschagrunert I think that I do not have permission to restart the Github action.

**Comment by ccojocar** [comment]
@saschagrunert Please could you lgtm this one again? Thanks

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
