### PR TITLE
`spoc record` fixes

### PR DESCRIPTION
**Pull request by mhils**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

This PR fixes ~two~ six bugs with the recorder - see the individual commits for detailed descriptions. :)

#### Which issue(s) this PR fixes:

None

#### Does this PR have test?

No.

#### Does this PR introduce a user-facing change?

```release-note
Fix `spoc record` to work with >15 character executable names.
Make AppArmor profile generation more robust.
```

### CODE REVIEW

**Comment by mhils** [comment]
This PR here is ready. But if I rebase it onto main, nix-build is hanging indefinitely while compiling LLVM on my system. Still need to figure out what's up with that. 🤷

**Review by ccojocar — APPROVED** [review]

**Comment by ccojocar** [comment]
@mhils I think PR needs a rebase. Thanks

**Comment by mhils** [comment]
Thanks y'all. I have added four more commits with various AppArmor-related fixes that should all be super uncontroversial. :)

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
