### PR TITLE
Add mock-able profile binding implementation

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
We now add a mock-able profile binding implementation which can be later
on used to add unit tests to the `binding` package.

#### Which issue(s) this PR fixes:

None
#### Does this PR have test?
None

#### Special notes for your reviewer:
I'll follow up on the unit tests if this PR got merged.
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by JAORMX — APPROVED** [review]
/lgtm

**Comment by JAORMX** [comment]
Looks like a legitimate issue:
```
         --- FAIL: TestSuite/TestSecurityProfilesOperator/cluster-wide:_Seccomp:_Verify_profile_binding (10.56s) 
```

The profile binding no longer has the appropriate finalizer:
```
 time="2021-04-09T12:35:21Z" level=info msg="+ /usr/local/bin/kubectl config view --minify -o jsonpath={..namespace}"
I0409 12:35:21.800273    6694 suite_test.go:445]  "msg"="Testing that pod has securityContext"  
time="2021-04-09T12:35:21Z" level=info msg="+ /usr/local/bin/kubectl get pod hello --output jsonpath={.spec.containers[0].securityContext.seccompProfile.localhostProfile}"
operator/default/profile-allow-unsafe.jsonI0409 12:35:21.901117    6694 suite_test.go:445]  "msg"="Testing that profile binding has pod reference"  
time="2021-04-09T12:35:21Z" level=info msg="+ /usr/local/bin/kubectl get profilebinding hello-binding --output jsonpath={.status.activeWorkloads[0]}"
default/hellotime="2021-04-09T12:35:22Z" level=info msg="+ /usr/local/bin/kubectl get profilebinding hello-binding --output jsonpath={.metadata.finalizers[0]}"
    tc_profilebindings_test.go:108: 
        	Error Trace:	tc_profilebindings_test.go:108
        	            				e2e_test.go:109
        	            				suite.go:77
        	Error:      	Not equal: 
        	            	expected: "active-workload-lock"
        	            	actual  : ""
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-active-workload-lock
        	            	+
        	Test:       	TestSuite/TestSecurityProfilesOperator/cluster-wide:_Seccomp:_Verify_profile_binding
```

**Comment by saschagrunert** [comment]
Let's see if the latest push can resolve the mentioned issue.

**Comment by saschagrunert** [comment]
@JAORMX PTAL

**Pull request merged**
