### PR TITLE
Switch to clang 14 for debian based tests

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind failing-test

#### What this PR does / why we need it:
Downgrading clang in the verify job to 14 to fix the broken packages.

#### Which issue(s) this PR fixes:

None
#### Does this PR have test?
None

#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
@kubernetes-sigs/security-profiles-operator-maintainers PTAL

**Review by jhrozek — APPROVED** [review]
/lgtm

**Pull request merged**
