### PR TITLE
Re-enable vulnerability scanning for build-image

### PR DESCRIPTION
**Pull request by ccojocar**
#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]

**Comment by ccojocar** [comment]
@saschagrunert Do you have an idea how to fix this out of memory issue? It happens when the image gets loaded for next step does the vulnerability scanning. 

```
#15 ERROR: write /nix/store/.links/18fjcppqdyw10vsra8jyp0szl57zl23idqcd62sf9df0xa5vy82a: no space left on device

#14 exporting to docker image format
#14 sending tarball 147.1s done
#14 ERROR: rpc error: code = Unknown desc = write /nix/store/.links/18fjcppqdyw10vsra8jyp0szl57zl23idqcd62sf9df0xa5vy82a: no space left on device
------
 > exporting to docker image format:
------
------
 > importing to docker:
------
ERROR: failed to solve: rpc error: code = Unknown desc = write /nix/store/.links/18fjcppqdyw10vsra8jyp0szl57zl23idqcd62sf9df0xa5vy82a: no space left on device
Error: buildx failed with: ERROR: failed to solve: rpc error: code = Unknown desc = write /nix/store/.links/18fjcppqdyw10vsra8jyp0szl57zl23idqcd62sf9df0xa5vy82a: no space left on device
```

**Review by JAORMX — APPROVED** [review]

**Comment by saschagrunert** [comment]
> @saschagrunert Do you have an idea how to fix this out of memory issue? It happens when the image gets loaded for next step does the vulnerability scanning.


This looks like a flake :thinking:

**Comment by ccojocar** [comment]
> Actually not, it really looks like that we're running out of resources. 🤔

Yeah, it seems that the maximum disk space of the action is exceeded.  I am not sure if we can reclaim more storage from nix after building the packages to reduce some more space. I think we already run some garbage collection in the Dockerfile.

**Comment by ccojocar** [comment]
@saschagrunert I managed to reduce the build-image size from 14GB to 8GB. There are some vulnerabilities returned by the scan but we didn't fail the build for them in the past. I think you can lgtm this. Thanks

**Review by saschagrunert — APPROVED** [review]
Thank you!

**Pull request merged**
