### PR TITLE
Add Initial Support for AppArmor Profile Merging

### PR DESCRIPTION
**Pull request by mhils**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

This PR adds profile merging for AppArmor profiles. While the in-cluster recording parts aren't quite there yet, it already works with `spoc merge`. There are more optimizations we could do here (most importantly merging profiles with wildcard paths), but this is a start. :)

#### Which issue(s) this PR fixes:

refs (but not fixes) #718

#### Does this PR have test?

Yes.

#### Does this PR introduce a user-facing change?

```release-note
Added initial support for merging AppArmor profiles with `spoc merge`.
```

### CODE REVIEW

**Comment by mhils** [comment]
Rebased onto main and tests pass locally. Let me know if this needs anything else! 😃

**Comment by mhils** [comment]
> The ubi image tests is a bit tricky since we have to wait for a new golang release on their end.

Any preferences on your end? Happy to wait for now, also happy to manually implement compacting. :)

**Comment by saschagrunert** [comment]
> happy to manually implement compacting

Yeah let's use a utility function with a TODO :+1:

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
