### PR TITLE
Make log verbosity usable

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
We hack around klog to make the log verbosity actually usable either by
using the `-V` flag or the `SPO_VERBOSITY` environment variable.

#### Which issue(s) this PR fixes:

None
#### Does this PR have test?
None

#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
Added CLI flag `-V` and environment variable parsing `SPO_VERBOSITY` to set the logging verbosity.
```

### CODE REVIEW

**Review by jhrozek — COMMENTED** [review]
I think the code is good, but I also think it would be nice to touch up installation-usage.md. There is a troubleshooting section that might benefit from having this information.

**Comment by saschagrunert** [comment]
> I think the code is good, but I also think it would be nice to touch up installation-usage.md. There is a troubleshooting section that might benefit from having this information.

How about adding a new feature in the spod config to enable debug logs? This way the operator can take care of adding the env to the daemon set.

I can follow up on that if we think it's a good idea.

**Comment by jhrozek** [comment]
On Thu, Nov 11, 2021 at 04:12:26AM -0800, Sascha Grunert wrote:
> > I think the code is good, but I also think it would be nice to touch up installation-usage.md. There is a troubleshooting section that might benefit from having this information.
> 
> How about adding a new feature in the spod config to enable debug logs? This way the operator can take care of adding the env to the daemon set.
> 
> I can follow up on that if we think it's a good idea.

I like this!

**Comment by saschagrunert** [comment]
> I like this!

Thanks, can we merge this one then? :upside_down_face:

**Review by jhrozek — APPROVED** [review]
/lgtm

**Pull request merged**
