### PR TITLE
Add jhrozek and JAORMX as approvers

### PR DESCRIPTION
**Pull request by jhrozek**
#### What type of PR is this?
/kind feature

(I guess?)

#### What this PR does / why we need it:
It would be nice to have more contributors that are based in EU as approvers.

#### Which issue(s) this PR fixes:
None

#### Does this PR have test?
N/A

#### Special notes for your reviewer:
N/A

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by jhrozek** [comment]
@saschagrunert @pjbgf @hasheddan

**Review by JAORMX — APPROVED** [review]

**Comment by pjbgf** [comment]
It's `/lgtm` and `/approve` from me. But keen on getting @saschagrunert's views first.

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
