### PR TITLE
deploy: make sure that manifests start with a separator

### PR DESCRIPTION
**Pull request by jhrozek**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Our operator-sdk bundle build command cat(1)s several files together,
but since the CSV, which is the last in the list, was missing a
separator on the first line, the last YAML object in the previous file
(deployment.yaml) was concatenated with the CSV.

Let's make sure the YAML documents in deploy/base start with a
separator.

#### Which issue(s) this PR fixes:
None

#### Does this PR have test?
N/A will be tested by the existing ones

#### Special notes for your reviewer:
N/A

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by JAORMX — APPROVED** [review]
good catch!
/lgtm
/approve

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
