### PR TITLE
selinux: Remove dead code

### PR DESCRIPTION
**Pull request by jhrozek**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Most of this code was unused for some time except for one utility
function that was folded into the selinux controller as a condition as
it was only used on that single place.

#### Which issue(s) this PR fixes:
None

#### Does this PR have test?
N/A

#### Special notes for your reviewer:
N/A

#### Does this PR introduce a user-facing change?

```release-note
NONE

```

### CODE REVIEW

**Comment by jhrozek** [comment]
rebased on top of the recent CI changes

**Comment by pjbgf** [comment]
nice one @jhrozek 👍 

/lgtm
/approve

**Pull request merged**
