### PR TITLE
Deploy default profiles via the manager

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
We now deploy the default profiles at the same time where the daemonset
gets deployed. This allows users to use them either in the
`security-profiles-operator` namespace (default) or in the provided
namespace.
#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes-sigs/security-profiles-operator/issues/267
#### Does this PR have test?

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
Automatically deploy the default profiles in the correct namespace without having a need for an additional `kubectl apply` command.
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
Alright I have to fixup the e2e tests first…

**Comment by cmurphy** [comment]
@saschagrunert here's a fix https://github.com/kubernetes-sigs/security-profiles-operator/pull/271 although I think the latest hello-world image tag may have fixed it anyways

**Comment by saschagrunert** [comment]
> @saschagrunert here's a fix #271 although I think the latest hello-world image tag may have fixed it anyways

Thanks! Another issue was that we still have to remove the profiles before deleting the operator. Added this hint to the docs.

**Review by pjbgf — APPROVED** [review]
/lgtm

**Pull request merged**
