### PR TITLE
Fix SeccompProfile status RBAC

### PR DESCRIPTION
**Pull request by cmurphy**
The controller was missing the ability to update a SeccompProfile's
status from 2050924 (probably a rebase error). This change fixes the
RBAC so that the status can be updated and permissions errors aren't
clogging up the logs.

#### What type of PR is this?

/kind bug

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by cmurphy** [comment]
Just noticed this was missing, I might have dropped it during a rebase or something

**Review by hasheddan — APPROVED** [review]
/lgtm

**Review by saschagrunert — APPROVED** [review]
/lgtm

🙏

**Comment by saschagrunert** [comment]
The tests have been displayed as successful but obviously did not run because of the missing ok-to-test…

**Pull request merged**
