### PR TITLE
Init the README.md for spo

### LINKED ISSUE #1194: Use helm-docs to auto-generate helm documentation
#### What would you like to be added:
The user experience for those installing SPO via the helm chart could be improved by using a tool like https://github.com/norwoodj/helm-docs to auto-generate documentation around the values available to the helm-chart.

#### Why is this needed:

Currently, a user would need to dig through both the values file and the templates themselves to discover what settings are available to the helm chart.

#### User story covered

As a User
I would like to be able to easily discover available SPO settings in the helm chart
so that I could deploy SPO with an appropriate configuration

### PR DESCRIPTION
**Pull request by chenliu1993**
#### What type of PR is this?
/kind documentation

#### Which issue(s) this PR fixes:
Fixes #1194 

#### Does this PR have test?
N/A
Simply install the chart locally

#### Does this PR introduce a user-facing change?

```release-note
Add a README.md to make user easily discover available SPO settings in the helm chart
```

### CODE REVIEW

**Comment by chenliu1993** [comment]
I left some fields from values.yaml because I think they are not used currently

**Review by saschagrunert — APPROVED** [review]
Thank you!

**Pull request merged**
