### PR TITLE
Make log enricher work with containerd

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
This should make the CRI-O requirement obsolete and also work on containerd.
#### Which issue(s) this PR fixes:

None
#### Does this PR have test?
None

#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
Have to verify that it actually works.

**Comment by saschagrunert** [comment]
Tested in ubuntu, microk8s and installed auditd:
```
I0624 08:16:33.540285   39923 enricher.go:111] log-enricher "msg"="audit"  "container"="log-container" "executable"="/usr/sbin/nginx" "namespace"="security-profiles-operator" "node"="ubuntu-hirsute" "pid"=43313 "pod"="log-pod" "syscallID"=16 "syscallName"="ioctl" "timestamp"="1624522556.801:3021" "type"="seccomp"
I0624 08:16:33.551466   39923 enricher.go:111] log-enricher "msg"="audit"  "container"="log-container" "executable"="/usr/sbin/nginx" "namespace"="security-profiles-operator" "node"="ubuntu-hirsute" "pid"=43311 "pod"="log-pod" "syscallID"=3 "syscallName"="close" "timestamp"="1624522556.801:3022" "type"="seccomp"
I0624 08:16:33.560159   39923 enricher.go:111] log-enricher "msg"="audit"  "container"="log-container" "executable"="/usr/sbin/nginx" "namespace"="security-profiles-operator" "node"="ubuntu-hirsute" "pid"=43313 "pod"="log-pod" "syscallID"=206 "syscallName"="io_setup" "timestamp"="1624522556.801:3023" "type"="seccomp"
I0624 08:16:33.638312   39923 enricher.go:111] log-enricher "msg"="audit"  "container"="log-container" "executable"="/usr/sbin/nginx" "namespace"="security-profiles-operator" "node"="ubuntu-hirsute" "pid"=43311 "pod"="log-pod" "syscallID"=233 "syscallName"="epoll_ctl" "timestamp"="1624522556.801:3024" "type"="seccomp"
I0624 08:16:33.656041   39923 enricher.go:111] log-enricher "msg"="audit"  "container"="log-container" "executable"="/usr/sbin/nginx" "namespace"="security-profiles-operator" "node"="ubuntu-hirsute" "pid"=43311 "pod"="log-pod" "syscallID"=232 "syscallName"="epoll_wait" "timestamp"="1624522556.801:3025" "type"="seccomp"
I0624 08:16:33.665089   39923 enricher.go:111] log-enricher "msg"="audit"  "container"="log-container" "executable"="/usr/sbin/nginx" "namespace"="security-profiles-operator" "node"="ubuntu-hirsute" "pid"=43313 "pod"="log-pod" "syscallID"=233 "syscallName"="epoll_ctl" "timestamp"="1624522556.801:3026" "type"="seccomp"
```

**Comment by saschagrunert** [comment]
@JAORMX @jhrozek PTAL

**Comment by JAORMX** [comment]
/lgtm

awesome!

**Pull request merged**
