### PR TITLE
Bump back to dev

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
Bump the images back to the development version.
#### Which issue(s) this PR fixes:

Refers to https://github.com/kubernetes-sigs/security-profiles-operator/issues/799
#### Does this PR have test?
None

#### Special notes for your reviewer:
/hold
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
@pjbgf PTAL

**Review by JAORMX — APPROVED** [review]

**Pull request merged**
