### PR TITLE
Add parallel bpf recording e2e test

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
This test ensures that parallel recording works as intended.

#### Which issue(s) this PR fixes:

None
#### Does this PR have test?
Yes

#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by JAORMX** [comment]
@saschagrunert mind rebasing this so the GH actions run again?

otherwise lgtm

**Comment by saschagrunert** [comment]
> @saschagrunert mind rebasing this so the GH actions run again?

Sure, gave it a rebase.

**Pull request merged**
