### PR TITLE
Bump golangci to 1.43.0

### PR DESCRIPTION
**Pull request by jhrozek**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Let's stay up2date

#### Which issue(s) this PR fixes:
None

#### Does this PR have test?
N/A

#### Special notes for your reviewer:
N/A

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]

**Comment by jhrozek** [comment]
@saschagrunert @pjbgf PTAL.

I'm not very happy myself with adding so many new skip files listed one by one and also not super happy about following master for the the boilerplate verify script. Makes me wonder if we should stay on an older version of golangci..

**Comment by pjbgf** [comment]
> I'm not very happy myself with adding so many new skip files listed one by one and also not super happy about following master for the the boilerplate verify script. Makes me wonder if we should stay on an older version of golangci..

@jhrozek I am more concerned with following `master` for the boilerplate script. I would probably wait until a new version is cut so we can pin it.
I agree that the cost vs benefit of upgrading `golangci` does not look appealing - mainly for the point above.

**Comment by jhrozek** [comment]
> > I'm not very happy myself with adding so many new skip files listed one by one and also not super happy about following master for the the boilerplate verify script. Makes me wonder if we should stay on an older version of golangci..
> 
> @jhrozek I am more concerned with following `master` for the boilerplate script. I would probably wait until a new version is cut so we can pin it. I agree that the cost vs benefit of upgrading `golangci` does not look appealing - mainly for the point above.

Oops, the patch was merged. I'm glad for the feedback, though and had a similar concern. Feel free to post a revert so that this gets properly discussed.

**Comment by pjbgf** [comment]
@jhrozek that's fine. I think we can just wait for the `repo-infra` to cut a version and then we pin it back to it.

**Pull request merged**
