### PR TITLE
Rename seccomp-operator to security-profiles-operator

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:
Renaming the operator to it's new proposed name.

#### Which issue(s) this PR fixes:

Refers to https://github.com/kubernetes/org/issues/2177
#### Special notes for your reviewer:
/hold
#### Does this PR introduce a user-facing change?

```release-note
Renamed seccomp-operator to security-profiles-operator
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
Depends on https://github.com/kubernetes/test-infra/pull/19476

**Review by hasheddan — APPROVED** [review]
/lgtm

after necessary infra changes land :+1:

**Review by pjbgf — APPROVED** [review]
/lgtm

once the two dependent PRs gets merged.

**Comment by cmurphy** [comment]
lgtm :+1:

**Comment by saschagrunert** [comment]
@pjbgf @hasheddan @cmurphy PTAL, encountering green tests.

**Pull request merged**
