### PR TITLE
Bump version to v0.3.0-dev

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
Bump VERSION back to the next development version.
#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
/hold
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by hasheddan — APPROVED** [review]
/lgtm

**Comment by saschagrunert** [comment]
This needs another set of approvals 
/assign @hasheddan

**Review by hasheddan — APPROVED** [review]
/lgtm

**Pull request merged**
