### PR TITLE
Remove leftover TODO

### PR DESCRIPTION
**Pull request by JAORMX**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Removes leftover TODO comment

#### Which issue(s) this PR fixes:

None

#### Does this PR have test?

N/A.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by JAORMX** [comment]
... I thought the flakiness had been addressed... I'll look into this tomorrow.

/retest

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
