### PR TITLE
feat: add the ActNotify to the list of allowed seccomp actions

### PR DESCRIPTION
**Pull request by ccojocar**
#### What type of PR is this?

/kind feature 

#### What this PR does / why we need it:

Add the ActNotify to the list of allowed seccomp actions. This has required to update the github.com/containers/common to latest version in order to get this change https://github.com/containers/common/pull/1027. 

#### Does this PR introduce a user-facing change?

```release-note
Add SCMP_ACT_NOTIFY to the list of allowed seccomp actions
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]

**Comment by saschagrunert** [comment]
/ok-to-test

Great contribution to c/common, thank you!

**Review by JAORMX — APPROVED** [review]

**Comment by ccojocar** [comment]
@saschagrunert Please could you add again the lgtm label? All tests are green now. Thanks!

**Pull request merged**
