### PR TITLE
Add jhrozek to reviewers

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
@jhrozek continuous contributions to this project should be honored by
applying the `reviewers` role.
#### Which issue(s) this PR fixes:

None
#### Does this PR have test?
None

#### Special notes for your reviewer:

Question to @jhrozek: Do you want to be a reviewer for this project?

(You have to be part of the Kubernetes org to be able to do so, which means that this PR can be merged only afterwards)

/hold 
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by jhrozek** [comment]
> The following users are mentioned in OWNERS file(s) but are untrusted for the following reasons. One way to make the user trusted is to add them as [members](https://git.k8s.io/community/community-membership.md#member) of the kubernetes-sigs org. You can then trigger verification by writing `/verify-owners` in a comment.
> 
>     * jhrozek
>       
>       * User is not a member of the org. Satisfy at least one of these conditions to make the user trusted.

I received and accepted the invitations to both kubernetes and kubernetes-sigs

**Review by saschagrunert — COMMENTED** [review]
/lgtm

**Comment by saschagrunert** [comment]
> @saschagrunert: you cannot LGTM your own PR.

Every time worth a try.

**Comment by saschagrunert** [comment]
Merging, this change will not affect the CI.

**Pull request merged**
