### PR TITLE
olm: Use file-based catalog instead of SQLite based catalog

### LINKED ISSUE #1203: Convert the catalog image to file-based from SQLite-based
#### What happened:
OLM has deprecated the SQLite based catalog we use upstream in favour of file-based catalogs. On some distributions (OCP), the SQLite catalogs are already causing problems on OCP 4.12+. Already, users are seeing a deprecation warning and if the catalog happens to be rebuild with an older OPM image it won't work at all.

#### What you expected to happen:
No deprecation warnings

#### How to reproduce it (as minimally and precisely as possible):
Install SPO from the upstream catalogSource

#### Anything else we need to know?:
https://olm.operatorframework.io/docs/reference/file-based-catalogs/

#### Environment:

- Cloud provider or hardware configuration: AWS
- OS (e.g: `cat /etc/os-release`): RHCOS
- Kernel (e.g. `uname -a`): N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by jhrozek**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Since OLM is deprecating the SQLite based catalog we are currently
using, while at the same time, the SQLite based catalogs have issues
interacting with OpenShift clusters that implement the recent PSA
changes, let's switch to file-based catalog:
    https://olm.operatorframework.io/docs/reference/file-based-catalogs/

Note: this change only affects upstream. Downstream catalogs (such as the
one OCP produces for RH-shipped operators) already employed a workaround.

Most of the work is done by the "opm render" command except for some
metadata that is stored at catalog/preamble.json, for example the icon.

#### Which issue(s) this PR fixes:
Fixes #1203

#### Does this PR have test?
will be tested by the OLM test

#### Special notes for your reviewer:
N/A

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by jhrozek** [comment]
oops I managed to commit a change that was only meant for testing:
```
         {
-            "name": "security-profiles-operator.v0.6.0",
-            "skipRange": ">=0.4.1 <0.6.0"
+            "name": "security-profiles-operator.v0.5.1-dev",
+            "skipRange": ">=0.4.1 <0.5.1-dev"
         }
```
sorry!

**Review by JAORMX — COMMENTED** [review]
Is this ready for merging?

**Comment by jhrozek** [comment]
> Is this ready for merging?

sadly, no. The OLM tests are not passing and I need to look into that. I did test the catalog on OCP, but I need to dig into the tests to see what's up (maybe we use too old OLM version there?).

**Comment by jhrozek** [comment]
note for self: check if operatorhub.io supports file-based catalogs.

**Comment by jhrozek** [comment]
/hold 
till I figure out the olm tests

**Comment by jhrozek** [comment]
next bug:
```
2022/10/23 08:00:09 render reference "localhost:5000/security-profiles-operator-bundle:v720b17fbedf8e7a2368c304ab342b72b771d3912": error resolving name : failed to do request: Head "https://localhost:5000/v2/security-profiles-operator-bundle/manifests/v720b17fbedf8e7a2368c304ab342b72b771d3912": http: server gave HTTP response to HTTPS client
```

**Comment by jhrozek** [comment]
On Sun, Oct 23, 2022 at 01:01:03AM -0700, Jakub Hrozek wrote:
> next bug:
> ```
> 2022/10/23 08:00:09 render reference "localhost:5000/security-profiles-operator-bundle:v720b17fbedf8e7a2368c304ab342b72b771d3912": error resolving name : failed to do request: Head "https://localhost:5000/v2/security-profiles-operator-bundle/manifests/v720b17fbedf8e7a2368c304ab342b72b771d3912": http: server gave HTTP response to HTTPS client

This seems to have been caused by OLM renaming the no-TLS parameter from
`skip-tls` to `use-http`. Because we are testing with a local registry
on a kind cluster, the registry only uses HTTP, not HTTPS so we need to
keep TLS disabled.

Let's see if the new patch fixes the tests..

**Comment by jhrozek** [comment]
green  tests, yay!
/hold cancel

**Comment by jhrozek** [comment]
On Fri, Oct 21, 2022 at 12:02:20PM -0700, Jakub Hrozek wrote:
> note for self: check if operatorhub.io supports file-based catalogs.

I was being dumb, one does upload bundles to operatorhub, not catalogs
and operatorhub creates a catalog. So our operatorhub.io releases are
not affected.

**Review by saschagrunert — APPROVED** [review]
Cool, the unit tests failed but I assume that’s the regular flake.

**Pull request merged**
