### PR TITLE
Helm chart CI linting

### PR DESCRIPTION
**Pull request by stephen-fox**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
This PR adds helm chart testing and linting to the CI process using the
"chart-testing" project:

  - https://github.com/helm/chart-testing
  - https://github.com/helm/chart-testing-action

#### Which issue(s) this PR fixes:
None.

#### Does this PR have test?
Yes.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by JAORMX** [comment]
/ok-to-test

Can you remove the WIP tag?

**Comment by JAORMX** [comment]
Seems you need to rebase

**Comment by stephen-fox** [comment]
Whoops. I think I forgot to merge `main` prior to my previous rebase.

**Comment by stephen-fox** [comment]
I updated the workflow name and added CI permissions like the other workflows.

The main reason I created a separate workflow config was to prevent merge conflicts. I am happy to combine it with `.github/workflows/test.yml` if desired.

**Pull request merged**
