### PR TITLE
e2e: Various stabilization fixes for our test suite

### PR DESCRIPTION
**Pull request by jhrozek**
#### What type of PR is this?
/kind bug
/kind flake

#### What this PR does / why we need it:
Since selinuxd switched to using policycoreutils, it is a bit slower.
Let's increase the number of iterations we wait for a policy to be
removed in hopes of getting a more stable CI environment.

#### Which issue(s) this PR fixes:
None

#### Does this PR have test?
N/A

#### Special notes for your reviewer:
N/A

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]

**Comment by jhrozek** [comment]
Going to try one more patch, hold in the meantime, I'm going to unhold when the PR is ready for review
/hold

**Comment by jhrozek** [comment]
Turning this into a PR with several assorted e2e fixes, going to unhold the PR when I'm done playing whack-a-mole.

**Review by JAORMX — APPROVED** [review]

**Comment by jhrozek** [comment]
fedora seems to be succeeding. flatcar failed with on the seccomp-metrics test which is still a little flaky. e2e (kind) based with a transient error where a pod didn't start.

I'm going to just close and reopen the PR to force the CI I think the situation has improved quite a bit with the patches.

**Comment by jhrozek** [comment]
OK, this is much better. @saschagrunert @JAORMX PTAL

Note that the metrics test is sometimes still a bit wonky, but that hits the kind-based e2e test mostly which can at least be re-run.
The reason is that the metrics service frontends the spod DS instances and for some reason (which I haven't figured out yet..) each pod in the DS reports a different metric value.

**Review by saschagrunert — APPROVED** [review]
Thank you! :pray:

**Pull request merged**
