### PR TITLE
Update golangci-lint version to v1.51.0

### PR DESCRIPTION
**Pull request by ccojocar**
#### What type of PR is this?

/kind bug

#### Does this PR introduce a user-facing change?

```release-note
Update golangci-lint to version 1.51.0.
```

### CODE REVIEW

**Comment by ccojocar** [comment]
I am not sure if this is the only place where needs to be updated.

**Comment by saschagrunert** [comment]
@ccojocar thanks! dependencies.yaml has to be updated for this as well.

**Comment by ccojocar** [comment]
@saschagrunert I updated also in `dependencies.yaml`. It seems that locally passed. Let's see the build.

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
