### PR TITLE
Update kind and it's k8s image

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
Update kind to the latest release and therefore it's k8s image.

#### Which issue(s) this PR fixes:

None
#### Does this PR have test?
None

#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by JAORMX — COMMENTED** [review]
/lgtm

**Comment by JAORMX** [comment]
For the record, the previous run failed with the following issues:
```
    tc_long_profile_name_test.go:58: 
        	Error Trace:	/home/prow/go/src/github.com/kubernetes-sigs/security-profiles-operator/tc_long_profile_name_test.go:58
        	            				/home/prow/go/src/github.com/kubernetes-sigs/security-profiles-operator/e2e_test.go:127
        	            				/home/prow/go/src/github.com/kubernetes-sigs/security-profiles-operator/suite.go:91
        	Error:      	Couldn't list statuses for nodes
        	Test:       	TestSuite/TestSecurityProfilesOperator/cluster-wide:_Seccomp:_make_sure_statuses_for_profiles_with_long_names_can_be_listed
...
    tc_long_profile_name_test.go:58: 
        	Error Trace:	/home/prow/go/src/github.com/kubernetes-sigs/security-profiles-operator/tc_long_profile_name_test.go:58
        	            				/home/prow/go/src/github.com/kubernetes-sigs/security-profiles-operator/e2e_test.go:182
        	            				/home/prow/go/src/github.com/kubernetes-sigs/security-profiles-operator/suite.go:91
        	Error:      	Couldn't list statuses for nodes
...
        --- FAIL: TestSuite/TestSecurityProfilesOperator/cluster-wide:_Seccomp:_make_sure_statuses_for_profiles_with_long_names_can_be_listed (1.63s)

...

        --- FAIL: TestSuite/TestSecurityProfilesOperator/namespaced:_Seccomp:_make_sure_statuses_for_profiles_with_long_names_can_be_listed (1.63s)
```

**Comment by JAORMX** [comment]
Gonna retest to see if this is consistent
/test all

**Comment by saschagrunert** [comment]
@JAORMX the e2e tests are now green :)

**Pull request merged**
