### PR TITLE
Switch back to dev VERSION

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
Switching back to dev after the release.
#### Which issue(s) this PR fixes:

Refers to #613 
#### Does this PR have test?
None

#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by jhrozek — APPROVED** [review]
/lgtm

**Review by pjbgf — APPROVED** [review]

**Pull request merged**
