### PR TITLE
Bump to v0.6.0

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:
Refers to https://github.com/kubernetes-sigs/security-profiles-operator/issues/1308
#### Which issue(s) this PR fixes:

None
#### Does this PR have test?
None

#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
PTAL @pjbgf @JAORMX @jhrozek @Vincent056 @ccojocar

**Review by pjbgf — APPROVED** [review]
/lgtm

thanks for picking up the release @saschagrunert. :bow: :bow: :bow:

**Pull request merged**
