### PR TITLE
Switch to go 1.21

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
Require the latest golang version.
#### Which issue(s) this PR fixes:

None
#### Does this PR have test?
None

#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
Updated project to require golang 1.21.
```

### CODE REVIEW

**Review by JAORMX — APPROVED** [review]

**Comment by saschagrunert** [comment]
@kubernetes-sigs/security-profiles-operator-maintainers this needs another LGTM

**Review by pjbgf — COMMENTED** [review]
/lgtm

**Pull request merged**
