### PR TITLE
Add `hack/release.sh` script

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:
The script helps to cut releases by automatically modifying the required sources.

#### Which issue(s) this PR fixes:

None
#### Does this PR have test?
None

#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by jhrozek — COMMENTED** [review]
The script looks good, did you already use it for 0.6.0?

**Comment by saschagrunert** [comment]
> The script looks good, did you already use it for 0.6.0?

No unfortunately not, but I thought it's now time to script that away. I'm also planning on adding a reverse script on top of that.

**Review by JAORMX — COMMENTED** [review]
should the helm chart release be included somewhere here too?

**Comment by saschagrunert** [comment]
> should the helm chart release be included somewhere here too?

Yes it is there: https://github.com/kubernetes-sigs/security-profiles-operator/pull/1323/files#diff-90c149c9bb54cd3c44ed74282439ab332af0be81f753e62dc37d2452c751390eR52

**Review by JAORMX — APPROVED** [review]

**Pull request merged**
