### PR TITLE
Add recording webhook unit tests

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
We now add a sufficient amount of unit tests for the profile recording
webhook.

#### Which issue(s) this PR fixes:

None
#### Does this PR have test?
Yes

#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
Rebased on the latest master branch.

**Review by JAORMX — COMMENTED** [review]
/lgtm

**Pull request merged**
