### PR TITLE
Remove crossplane-runtime dependency

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
This allows us to maintain our own status types and be faster on upgrades.
#### Which issue(s) this PR fixes:

None
#### Does this PR have test?
None

#### Special notes for your reviewer:
~~This seems to be a breaking API change.~~
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
@jhrozek @JAORMX @Vincent056 @ccojocar @pjbgf PTAL

**Comment by saschagrunert** [comment]
Trying to keep the API for backwards compatibility.

**Comment by pjbgf** [comment]
The changes looks good to me and I think this is a great step forward. Adding `/hold` to get views from other maintainers as well.

/lgtm
/hold

**Review by jhrozek — APPROVED** [review]
/lgtm
from me also. Thank you for working on these cleanups!

**Pull request merged**
