### PR TITLE
bundle: Add OCP-specific cluster monitoring annotation

### PR DESCRIPTION
**Pull request by jhrozek**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
When installing an operator through the OpenShift console, the
`operatorframework.io/cluster-monitoring: "true"` CSV annotation tells the
console to annotate the namespace with `openshift.io/cluster-monitoring=true`
as well which means that metrics will be gathered without any additional
action.

#### Which issue(s) this PR fixes:
None

#### Does this PR have test?
No, this is OCP-specific

#### Special notes for your reviewer:
N/A

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
LGTM, let's rebase this one as well.

**Comment by jhrozek** [comment]
> LGTM, let's rebase this one as well.

Rebased with no other changes.

**Comment by jhrozek** [comment]
```
Github rate-limiter failed the request. Either authenticate or wait a couple of minutes.
```
gotta retry later probably

**Comment by jhrozek** [comment]
Rebased atop the flatcar test fixes again

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
