### PR TITLE
Add End-to-End Tests for Spoc

### PR DESCRIPTION
**Pull request by mhils**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

I have a series of (work-in-progress) BPF recorder improvements sitting at https://github.com/kubernetes-sigs/security-profiles-operator/compare/main...mhils:security-profiles-operator:wip that I'd like to upstream. I'd like to kick this off with end-to-end tests for spoc so that we have more confidence in further PRs. :)

#### Which issue(s) this PR fixes:

refs (but not fixes) https://github.com/kubernetes-sigs/security-profiles-operator/issues/718

#### Does this PR have test?

Yes.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by mhils** [comment]
I've rebased onto main and made sure that tests are passing locally. Please let me know if this needs anything else! 😃

**Review by saschagrunert — COMMENTED** [review]
Thank you for working on this! :pray:

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
