### PR TITLE
apparmor: Add AppArmor info at start time

### PR DESCRIPTION
**Pull request by pjbgf**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Provides additional information for users using AppArmor to debug potential setup issues.
An example of what the SPO will write onto logs at the start:

```
I0809 18:39:30.678856   21442 apparmorprofile.go:279] apparmor-spod "msg"="detecting apparmor support..." 
I0809 18:39:30.679580   21442 apparmorprofile.go:286] apparmor-spod "msg"="apparmor enabled: OK" 
I0809 18:39:30.679682   21442 apparmorprofile.go:289] apparmor-spod "msg"="apparmor fs:  (appArmor mount point: could not complete operation)" 
I0809 18:39:30.679768   21442 apparmorprofile.go:292] apparmor-spod "msg"="apparmor enforceable: OK" 
```

#### Which issue(s) this PR fixes:

None

#### Does this PR have test?

N/A

#### Does this PR introduce a user-facing change?

```release-note
Additional debug information about AppArmor state is now provided at start-up.
```

### CODE REVIEW

**Comment by pjbgf** [comment]
Noticed that some dependencies were being downgraded as part of the change - reverted such changes.

**Comment by jhrozek** [comment]
This linter warning is confusing:
```
 internal/pkg/daemon/apparmorprofile/apparmorprofile.go:29:2: Expected 'a', Found 'c' at internal/pkg/daemon/apparmorprofile/apparmorprofile.go[line 29,col 2] (gci)
	ctrl "sigs.k8s.io/controller-runtime" 
```
but it pretty much means that the imports must be sorted alphabetically. I think the linter has a `--fix` option that should do all that.

**Comment by jhrozek** [comment]
the code looks OK to me btw

**Comment by pjbgf** [comment]
@jhrozek thank you for the review and pointing out the linter issue. PTAL

**Review by jhrozek — APPROVED** [review]
/lgtm

**Pull request merged**
