### PR TITLE
Three minor patches

### PR DESCRIPTION
**Pull request by jhrozek**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
See the commit messages for details, but tl;dr SPO didn't work well on
OpenShift.

#### Which issue(s) this PR fixes:
None

#### Does this PR have test?
None

#### Special notes for your reviewer:
None

#### Does this PR introduce a user-facing change?

```release-note
NONE

```

### CODE REVIEW

**Comment by jhrozek** [comment]
Umm, huh?
```
Error:      	"fatal error: runtime: cannot allocate memory
```
let me rebase and try again..

**Comment by saschagrunert** [comment]
> Umm, huh?

Hrnhghh.

**Review by saschagrunert — APPROVED** [review]

**Comment by saschagrunert** [comment]
I think tide merged in between two tests. There is a small gap between reporting dependent steps in GitHub actions.

**Comment by jhrozek** [comment]
On Thu, May 06, 2021 at 02:28:06AM -0700, Sascha Grunert wrote:
> I think tide merged in between two tests. There is a small gap between reporting dependent steps in GitHub actions.

The test failed with "error: the server doesn't have a resource type
"spod"" which I think is not related to these patches..

**Pull request merged**
