### PR TITLE
Bump to v0.7.1

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
Preparing for the Monday release.
/hold
#### Which issue(s) this PR fixes:

None
#### Does this PR have test?

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by ccojocar — APPROVED** [review]

**Comment by jhrozek** [comment]
/test pull-security-profiles-operator-test-e2e
looks like some sort of a timeout

**Comment by saschagrunert** [comment]
@kubernetes-sigs/security-profiles-operator-maintainers PTAL

**Review by jhrozek — APPROVED** [review]
/lgtm

**Pull request merged**
