### PR TITLE
Pass pre-build operator image to e2e test

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
We now pre-build the operators container image and pass it over to the
VM to speedup the CI.
#### Which issue(s) this PR fixes:

None
#### Does this PR have test?

Yes
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by hasheddan — APPROVED** [review]
/lgtm

**Review by JAORMX — APPROVED** [review]

**Review by JAORMX — COMMENTED** [review]
/lgtm

**Comment by saschagrunert** [comment]
:thinking: 
```
    default: ++ sudo podman load -i /vagrant/image.tar
    default:   open /vagrant/image.tar/manifest.json: no such file or directory
    default:   open /vagrant/image.tar/index.json: no such file or directory
    default: Error: error pulling "": Invalid image localhost/
```

**Comment by saschagrunert** [comment]
Ah it's the download artifacts path which will be converted into a directory… Now it should work :crossed_fingers:

**Pull request merged**
