### PR TITLE
Bump repo-infra version

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
This bumps Kubernetes to the latest patch release as well as repo-infra.

#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by hasheddan — APPROVED** [review]
/lgtm

**Comment by saschagrunert** [comment]
No kind image for 1.19.3 yet, switching back to 1.19.2

**Comment by saschagrunert** [comment]
Even no 1.19.2 available :scream: , updating only repo-infra.

**Review by pjbgf — APPROVED** [review]
/lgtm

**Pull request merged**
