### PR TITLE
Improve webhook RBAC

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
Trim down the required RBAC for the webhook.
#### Which issue(s) this PR fixes:

None
#### Does this PR have test?
None

#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
@jhrozek @JAORMX PTAL

**Review by jhrozek — APPROVED** [review]
/lgtm
nice!

**Pull request merged**
