### PR TITLE
Create baseprofiles in CI

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
Creating the baseprofiles in the CI.
#### Which issue(s) this PR fixes:

None
#### Does this PR have test?
None

#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
Interestingly, the two syscalls `sched_yield` and `rt_sigreturn` see to flake in the test. :thinking: It may be related to application teardown…

**Comment by saschagrunert** [comment]
Happy tests!

@kubernetes-sigs/security-profiles-operator-maintainers PTAL

**Comment by saschagrunert** [comment]
@kubernetes-sigs/security-profiles-operator-maintainers  PTAL

**Review by ccojocar — APPROVED** [review]

**Pull request merged**
