### PR TITLE
Add bpf recorder unit tests

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
Just a few test cases have been added, the rest will follow in other PRs.
#### Which issue(s) this PR fixes:

None
#### Does this PR have test?
None

#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by jhrozek — APPROVED** [review]
/lgtm

**Comment by saschagrunert** [comment]
@pjbgf PTAL

**Comment by saschagrunert** [comment]
@jhrozek had to rebase if you don't mind giving another lgtm

**Review by pjbgf — COMMENTED** [review]
/lgtm

**Pull request merged**
