### PR TITLE
Make OLM tests less flaky

### LINKED ISSUE #2267: OLM tests are flaking
The tests are flaking recently: https://github.com/kubernetes-sigs/security-profiles-operator/actions/workflows/olm_tests.yaml

We should look into them to see how to stabilize the runs.

### PR DESCRIPTION
**Pull request by mhils**
#### What type of PR is this?

/kind failing-test
/kind flake

#### What this PR does / why we need it:

This PR makes OLM tests less flaky.

#### Which issue(s) this PR fixes:

fix #2267

#### Does this PR have test?

Yes

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by mhils** [comment]
OLM tests are fixed now, the remaining CI failures are unrelated.

**Review by ccojocar — APPROVED** [review]

**Comment by ccojocar** [comment]
> OLM tests are fixed now, the remaining CI failures are unrelated.

@saschagrunert Some new CVEs popped up,  I think we need to update the ubi image and the go version.

**Comment by saschagrunert** [comment]
/ok-to-test

Yes it looks like we have to wait for the CVE fixes.

**Comment by saschagrunert** [comment]
@mhils may I ask you to rebase?

**Comment by mhils** [comment]
Done!

**Review by saschagrunert — APPROVED** [review]

**Comment by ccojocar** [comment]
@mhils please could you rebase this pull request? It seems that tide is not able to rebase it. Thanks

**Comment by mhils** [comment]
I think these changes already made it in as part of https://github.com/kubernetes-sigs/security-profiles-operator/pull/2274, we're all set here! 😃

**Pull request closed without merging**
