### PR TITLE
Add operator deployment to GH actions e2e test

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
The oci hook works out of the box by the provided package. One thing we
have to consider is building the image locally as well as deploying the
operator based on that one. This is now going to be achieved with this
patch.
#### Which issue(s) this PR fixes:

None
#### Does this PR have test?

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by JAORMX — APPROVED** [review]
/lgtm

**Comment by JAORMX** [comment]
@saschagrunert most of this is currently done by the e2e test itself, what if we just cal make test-e2e and set the appropriate parameters instead?

**Comment by saschagrunert** [comment]
> @saschagrunert most of this is currently done by the e2e test itself, what if we just cal make test-e2e and set the appropriate parameters instead?

Hah, yeah sure I'll integrate the changes there
/hold

**Comment by JAORMX** [comment]
@saschagrunert trying it out in https://github.com/kubernetes-sigs/security-profiles-operator/pull/286

**Comment by saschagrunert** [comment]
> @saschagrunert trying it out in #286

Thanks!
/close

**Pull request closed without merging**
