### PR TITLE
Add seccomp error metrics

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
We now provide metrics about seccomp profile errors, while mapping the
event reasons to a label.
#### Which issue(s) this PR fixes:

Refers to #276 
#### Does this PR have test?

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
Added `seccomp_profile_error_total` metrics.
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
GitHub actions seems to be down, they do not get triggered. :thinking:

**Review by JAORMX — APPROVED** [review]
/lgtm

**Comment by JAORMX** [comment]
```
The box 'fedora/33-cloud-base' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Vagrant Cloud, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:
```

@saschagrunert @jhrozek sounds like it's getting more and more urgent to switch to f34

**Comment by saschagrunert** [comment]
> @saschagrunert @jhrozek sounds like it's getting more and more urgent to switch to f34

Hm, it seems to work locally on my machine.

**Comment by JAORMX** [comment]
@saschagrunert maybe you just gotta re-kick it

**Comment by saschagrunert** [comment]
> @saschagrunert maybe you just gotta re-kick it

Yeah I already did this multiple times. Giving it another try.

**Review by JAORMX — COMMENTED** [review]
/lgtm

**Pull request merged**
