### PR TITLE
Add ubuntu based e2e tests for log enricher

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Add an ubuntu based e2e test for syslog and containerd (or docker shim) testing.

#### Which issue(s) this PR fixes:

None

#### Does this PR have test?

Yes

#### Special notes for your reviewer:

None

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
This works and tests now via `/var/log/syslog` on Ubuntu and dockershim :upside_down_face:

**Review by JAORMX — APPROVED** [review]
/lgtm

yess!! More testing!

**Pull request merged**
