### PR TITLE
Add a base e2e test for apparmor

### PR DESCRIPTION
**Pull request by ccojocar**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

This e2e test covers the basic use case which loads and unloads apparmor profiles into the cluster nodes.

This is based on work done in #1074.

#### Which issue(s) this PR fixes:

Relates #718

#### Does this PR have test?

Yes

#### Does this PR introduce a user-facing change?

NONE

```release-note
Add a e2e test for apparmor profile which covers base functionlity such as loading and unloading profiles itno the cluster nodes.
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
Awesome, great work thank you!

**Comment by pjbgf** [comment]
Great job @ccojocar, thank you for working on this. :bow: 

/lgtm

**Pull request merged**
