### PR TITLE
Add streaming support for syscall recording

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
We now use the GRPC streaming capabilities to safe performance on syscall recording.
#### Which issue(s) this PR fixes:

None
#### Does this PR have test?
None

#### Special notes for your reviewer:
Requires https://github.com/kubernetes-sigs/security-profiles-operator/pull/513

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
Works, PTAL @JAORMX @jhrozek

**Review by jhrozek — COMMENTED** [review]
Looks good, but probably will have to be rebased atop the other streaming PR.

**Comment by saschagrunert** [comment]
Rebased to resolve the conflicts.

**Review by jhrozek — APPROVED** [review]
/lgtm

**Pull request merged**
