### PR TITLE
Add codecov badge

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:
Adding the badge to indicate the current unit test coverage.
#### Which issue(s) this PR fixes:

None
#### Does this PR have test?
None

#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by JAORMX — APPROVED** [review]
/lgtm

**Comment by saschagrunert** [comment]
Just a doc change
/skip

**Pull request merged**
