### PR TITLE
tests: Add the recording RBAC roles and SA dynamically, re-add on every operator redeploy

### PR DESCRIPTION
**Pull request by jhrozek**
#### What type of PR is this?
/kind bug
/kind failing-test

#### What this PR does / why we need it:
No idea why we didn't catch this before when running the RBAC roles and
SA on OCP before, but redeploying the operator wouldn't re-add the RBAC
role, role binding and the SA required to grant the ability to use the
SCC needed to record replicated controllers.

This patch adds the needed manifests as part of deploying the operator.

Note that most of the code is only executed on OCP, on other distros,
only the SA is added so that we can always reference the SA regardless
of the distribution.

#### Which issue(s) this PR fixes:
None

#### Does this PR have test?
N/A

#### Special notes for your reviewer:
N/A

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]

**Review by JAORMX — APPROVED** [review]

**Comment by jhrozek** [comment]
/hold
for some reason the tests work fine for me locally, wtf. Submitted some extra debugging and marking as hold

**Comment by jhrozek** [comment]
this PR now superseded PR #1015

**Comment by jhrozek** [comment]
@saschagrunert can you review this PR, please?

**Pull request merged**
