### PR TITLE
Change the github action runner for flatcar e2e test to use macos-13 image

### PR DESCRIPTION
**Pull request by ccojocar**
Install the missing dependencies such as virtualbox and upgrade vagrant to latest version

Signed-off-by: Cosmin Cojocar <gcojocar@adobe.com>

#### What type of PR is this?

/kind failing-test

#### Does this PR introduce a user-facing change?

```release-note
NONE

```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
Thank you!

**Comment by saschagrunert** [comment]
e2e tests still seem flaky in prow :thinking:

**Review by saschagrunert — APPROVED** [review]

**Comment by ccojocar** [comment]
The VM doesn't seem to start even though now we use the latest version of vagrant `2.3.7` and virtualbox `v7.0.8`. This combination seems to work fine on my local machine. 

Not sure what's different on GitHub action runtime when using macos-13 image (https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md). 

@tormath1 Do you have any idea what might cause the booting to stall? Unfortunately I cannot reproduce it locally? Thanks

**Comment by ccojocar** [comment]
This is the log messages from build:
```
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: security-profiles-operator_default_1687421693233_89737
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: core
    default: SSH auth method: private key
    default: Warning: Connection reset. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection reset. Retrying...
    default: Warning: Connection reset. Retrying...
```
It cannot open the ssh connection since I believe the VM is not booting. The Vagrantfile configuration is in https://github.com/kubernetes-sigs/security-profiles-operator/blob/b182e2c31359b88440785ceadbc86eb378e07f86/hack/ci/Vagrantfile-flatcar#L4.

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
