### PR TITLE
Back to v0.4.3-dev

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
Moving back to the development version.
#### Which issue(s) this PR fixes:

Closes https://github.com/kubernetes-sigs/security-profiles-operator/issues/879

#### Does this PR have test?
None

#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
Ready to be merged :)

**Review by jhrozek — APPROVED** [review]
/lgtm

**Pull request merged**
