### PR TITLE
Graduate seccomp profile from `v1alpha1` to `v1beta1`

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind api-change

#### What this PR does / why we need it:
Graduate the seccomp profile API. This also changes the imports to not mention the API version any more for easier graduation later on.
#### Which issue(s) this PR fixes:

None
#### Does this PR have test?
None

#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
Graduate seccomp profile API from `v1alpha1` to `v1beta1`
```

### CODE REVIEW

**Review by jhrozek — COMMENTED** [review]
I agree that seccomp in general has been stable enough to promote. And it would make a nice 0.4.0 release highlight. The only thing I wanted to change for a long time API-wise is to address issue #408. That's technically in the `secprofnodestatus` API though.

I'm explicitly not marking as LGTM because I think API graduation patches should have multiple reviewers. But, looks-good-to-me :-)

**Comment by JAORMX** [comment]
@jhrozek would solving #408 affect the API? I'm fine with deferring this graduation until that is solved.

**Comment by jhrozek** [comment]
On Wed, Nov 17, 2021 at 02:44:50AM -0800, Juan Osorio Robles wrote:
> @jhrozek would solving #408 affect the API? I'm fine with deferring this graduation until that is solved.

It will not (I actually took the time to carefully look at the code).

But let me fix 408 anyway, it's been open for too long :-)

**Comment by jhrozek** [comment]
> On Wed, Nov 17, 2021 at 02:44:50AM -0800, Juan Osorio Robles wrote: @jhrozek would solving #408 affect the API? I'm fine with deferring this graduation until that is solved.
> It will not (I actually took the time to carefully look at the code). But let me fix 408 anyway, it's been open for too long :-)

I opened the PR for 408 and it didn't change anything except a label. And because this PR has been open long enough for people to voice their opposition, I'm going to mark it for merging. If I screwed up, you can yell at me tomorrow over video.

**Review by jhrozek — APPROVED** [review]
/lgtm

**Pull request merged**
