### PR TITLE
Add Metrics for SELinux profiles

### PR DESCRIPTION
**Pull request by mrogers950**
This PR adds metrics updates for the SELinux profile functionality (mentioned in https://github.com/kubernetes-sigs/security-profiles-operator/issues/276#issuecomment-839636908)

```
# HELP security_profiles_operator_selinux_profile_error_total Counter about selinux profile errors.
# TYPE security_profiles_operator_selinux_profile_error_total counter                                   
security_profiles_operator_selinux_profile_error_total{reason="CannotUpdatePolicyStatus"} 1

# HELP security_profiles_operator_selinux_profile_total Counter about selinux profile operations.
# TYPE security_profiles_operator_selinux_profile_total counter
security_profiles_operator_selinux_profile_total{operation="delete"} 1
security_profiles_operator_selinux_profile_total{operation="update"} 6
```

```release-note
Add Metrics for SELinux profiles
```

@saschagrunert @jhrozek @JAORMX

### CODE REVIEW

**Review by saschagrunert — COMMENTED** [review]
Cool stuff! Docs have to be updated and linters have to be fixed now, too. :)

**Comment by mrogers950** [comment]
> Cool stuff! Docs have to be updated and linters have to be fixed now, too. :)

Thanks, I'll fix em

**Comment by mrogers950** [comment]
Fixed the last linter failure

**Comment by mrogers950** [comment]
For some reason we lost an update increment (I didn't think that was possible with prometheus metrics):
Maybe this is a known flake?
```
# HELP security_profiles_operator_seccomp_profile_error_total Counter about seccomp profile errors.
# TYPE security_profiles_operator_seccomp_profile_error_total counter
security_profiles_operator_seccomp_profile_error_total{reason="CannotUpdateNodeStatus"} 1
# HELP security_profiles_operator_seccomp_profile_total Counter about seccomp profile operations.
# TYPE security_profiles_operator_seccomp_profile_total counter
security_profiles_operator_seccomp_profile_total{operation="delete"} 11
security_profiles_operator_seccomp_profile_total{operation="update"} 11
pod "pod" deleted

.. after installing/deleting the profile ...

# TYPE security_profiles_operator_seccomp_profile_total counter
security_profiles_operator_seccomp_profile_total{operation="delete"} 12
security_profiles_operator_seccomp_profile_total{operation="update"} 10
pod "pod" deleted
I0608 16:59:35.369576    6875 suite_test.go:452]  "msg"="Asserting metrics values"  
	assertion_compare.go:323: 
			Error Trace:	tc_metrics_test.go:77
			            				e2e_test.go:109
			            				suite.go:77
			Error:      	"10" is not greater than or equal to "11"
			Test:       	TestSuite/TestSecurityProfilesOperator/cluster-wide:_Seccomp:_Metrics
			Messages:   	[]
=== RUN   TestSuite/TestSecurityProfilesOperator/cluster-wide:_Seccomp:_Re-deploy_the_operator
```

**Comment by JAORMX** [comment]
Can you add a release note?

**Comment by JAORMX** [comment]
@saschagrunert any idea why the Github actions didn't run in this PR?

**Review by saschagrunert — APPROVED** [review]
Very nice, thank you so much @mrogers950!

**Pull request merged**
