### PR TITLE
nodestatus: Remove dead code

### PR DESCRIPTION
**Pull request by jhrozek**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
The NewStatusReconciler function was unused since
4c28bcc12902aae3a3f81380a66993e798e0ae31

#### Which issue(s) this PR fixes:
None

#### Does this PR have test?
N/A

#### Special notes for your reviewer:
N/A

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by JAORMX — APPROVED** [review]
/lgtm
/approve

yay! code removals!

**Comment by jhrozek** [comment]
Looks like mirror issues with Debian:
```
   Could not connect to debian.map.fastlydns.net:80 (199.232.98.132), connection timed out Unable to connect to deb.debian.org:http: 
```

**Review by pjbgf — APPROVED** [review]
/lgtm

**Pull request merged**
