### PR TITLE
Reuse util.ContainerIDForPID in enricher

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
We now reuse the utility function to cleanup parts of the enricher
implementation.
#### Which issue(s) this PR fixes:

None
#### Does this PR have test?
None

#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
@pjbgf @jhrozek @JAORMX PTAL

**Review by jhrozek — APPROVED** [review]
The two implementations are pretty much the same
/lgtm

**Pull request merged**
