### PR TITLE
Update seccompprofile_types.go to change errnoRet to be of type uint

### PR DESCRIPTION
**Pull request by CoreyCook8**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

This PR changes the errnoRet to uint as defined here https://github.com/opencontainers/runtime-spec/blob/main/specs-go/config.go#L788C5-L788C5

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes-sigs/security-profiles-operator/issues/1769

#### Does this PR have test?
N/A

#### Does this PR introduce a user-facing change?
yes

```release-note
Changed errnoRet value in the seccomp types definition to be the right type of uint.
Fixed https://github.com/kubernetes-sigs/security-profiles-operator/issues/1769
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
Thank you for this PR @CoreyCook8 :pray: May I ask you to CLA sign-off your commit?

**Comment by CoreyCook8** [comment]
> Thank you for this PR @CoreyCook8 🙏 May I ask you to CLA sign-off your commit?

Yes, I am just trying to work out some EasyCLA issues 😅. Our CLA Manager is no longer with the team so we are working on fixing that!

**Comment by CoreyCook8** [comment]
Could I get some 👀 on this when someone has a moment? I would love to fix why these tests are failing but I can't really understand why they're failing from the messages 😬

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
