### PR TITLE
Use sync.Map for pods to watch

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
There is no guarantee for non-concurrent access of the state, so we
should lock that map accordingly.

#### Which issue(s) this PR fixes:

None
#### Does this PR have test?
None

#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by JAORMX — APPROVED** [review]
/lgtm

**Comment by JAORMX** [comment]
We do run unit tests with `-race`; this might have gotten caught with better unit test coverage. Might be worth adding more tests.

**Comment by saschagrunert** [comment]
This works now
/assign @JAORMX

**Review by JAORMX — COMMENTED** [review]
/lgtm

**Pull request merged**
