### PR TITLE
Switch to go 1.23

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
Switch to go 1.23.
#### Which issue(s) this PR fixes:

None
#### Does this PR have test?
None

#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by JAORMX — APPROVED** [review]

**Review by ccojocar — APPROVED** [review]

**Comment by saschagrunert** [comment]
Looks like `pull-security-profiles-operator-verify` hangs.

/hold

**Comment by saschagrunert** [comment]
/unhold

@kubernetes-sigs/security-profiles-operator-maintainers PTAL

**Pull request merged**
