### PR TITLE
Add arm64 support for bpf recorder

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
Adding arm64 support to the bpf recoder.
#### Which issue(s) this PR fixes:

None

#### Does this PR have test?

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
I tested it locally on a native arm Ubuntu 21.04 machine. PTAL @jhrozek @pjbgf

**Review by jhrozek — APPROVED** [review]
I can't say I'm a nix expert, so I'm fuzzy on the build stuff, but in general looks good
/lgtm

**Pull request merged**
