### PR TITLE
Add use case about correlating log entries to containers

### PR DESCRIPTION
**Pull request by pjbgf**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

Adds a new use case highlighting that Kirsti needs to be able to correlate audit logs to specific containers.

#### Which issue(s) this PR fixes:

None

#### Does this PR have test?

N/A

#### Special notes for your reviewer:

Follow-up from from [slack thread](https://kubernetes.slack.com/archives/C013FQNB0A2/p1614926114064100).

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by JAORMX — APPROVED** [review]
/lgtm

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Comment by JAORMX** [comment]
@pjbgf can you close and re-open this so the tests re-kick?

**Comment by saschagrunert** [comment]
> @pjbgf can you close and re-open this so the tests re-kick?

Re-triggered the test. You should be able to click on the test case below and restart the test suite via the button:
screenshot

**Comment by JAORMX** [comment]
@saschagrunert I don't have that button. Not even for my own PRs in this repo.

**Comment by saschagrunert** [comment]
> @saschagrunert I don't have that button. Not even for my own PRs in this repo.

Probably only approvers have :(

**Pull request merged**
