### PR TITLE
Add first enricher unit test

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
This patch adds the necessary infra for unit testing the enricher while
implementing a first success test.

Further tests will be added in other patches.
#### Which issue(s) this PR fixes:

None
#### Does this PR have test?
Yes

#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by JAORMX — APPROVED** [review]
/lgtm

**Comment by saschagrunert** [comment]
Had to rebase on top of the latest master branch.

**Comment by saschagrunert** [comment]
@JAORMX I need another LGTM on this one :upside_down_face:

**Pull request merged**
