### PR TITLE
WIP: Update btf code to fix build

### PR DESCRIPTION
**Pull request by pjbgf**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Upstream has recently split btfhub repo into two, this change updates our processes to accomodate such changes.

#### Which issue(s) this PR fixes:

None

#### Does this PR have test?

N/A

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by pjbgf** [comment]
@saschagrunert not sure whether this is the way to go. Running `make update-btf` generates over 500mb in changes, which may become a problem to store within the project's git index. 

I haven't commited/pushed the btf files, but running `go run ./internal/pkg/daemon/bpfrecorder/generate` locally fails after exhausting RAM memory. Thoughts?

**Comment by saschagrunert** [comment]
I’ll revisit this PR next week when I’m back in the office.

**Comment by saschagrunert** [comment]
Added the btf script fix to https://github.com/kubernetes-sigs/security-profiles-operator/pull/796 as well

**Comment by saschagrunert** [comment]
This can be closed now, thanks for looking into the issue @pjbgf! :pray:

**Pull request closed without merging**
