### PR TITLE
Clean up the "policy" field from ApparmorProfile CRD

### PR DESCRIPTION
**Pull request by ccojocar**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

This pull request is a follow-up on #2388 and removes complete the `policy` field from ApparmorProfile CRD. This field is not required anymore since all the content is generated from the `abstract`.

Additional work was done to fix the apparmor e2e tests, and to cleanup the code, manifests and documentation.

This work is a prerequisite for #2559.

#### Which issue(s) this PR fixes:

follow-up on #2388

#### Does this PR have test?

Yes

#### Does this PR introduce a user-facing change?

```release-note
API BREAKING CHANGES: policy field removed from ApparmorProfile CRD, use instead the abstract field which automatically generates the policy before installation.

```

cc @mhils

### CODE REVIEW

**Comment by ccojocar** [comment]
@saschagrunert I see also this issue locally, but the VM seem to work fine when I remove it completely:
```
    default: Loaded image: localhost/security-profiles-operator:latest
    default: ++ CNI_CONFIG=/etc/cni/net.d/10-crio-bridge.conflist
    default: ++ jq 'del(.plugins[0].ipam.routes[1], .plugins[0].ipam.ranges[1])' /etc/cni/net.d/10-crio-bridge.conflist
    default: jq: error: Could not open file /etc/cni/net.d/10-crio-bridge.conflist: No such file or directory
  ```
    
  Should we remove it from all VMs definitions?

**Comment by saschagrunert** [comment]
@ccojocar I have a fix in mind, one second.

**Comment by ccojocar** [comment]
> I have a fix in mind, one second: https://github.com/kubernetes-sigs/security-profiles-operator/pull/2594

@saschagrunert perfect, thanks a lot!

**Comment by saschagrunert** [comment]
Please rebase to fix the CI

**Comment by ccojocar** [comment]
@saschagrunert All tests passed, please could you have a look? Thanks

**Review by saschagrunert — APPROVED** [review]
Thank you!

**Pull request merged**
