### PR TITLE
Update kind node image to v1.20.0

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
This will bump the minor Kubernetes version for the e2e test suite.

#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by hasheddan — APPROVED** [review]
/lgtm

**Comment by saschagrunert** [comment]
Strange, locally it works but in the CI it seems to become not ready… :thinking:

**Pull request merged**
