### PR TITLE
Add crun to base profile e2e test

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
Since we now have a base profile for crun in place we can reuse the
existing test to switch them for the same scenario.

#### Which issue(s) this PR fixes:

None
#### Does this PR have test?
Yes

#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by hasheddan — APPROVED** [review]
/lgtm

**Comment by saschagrunert** [comment]
Let me give an updated crun a try.

**Comment by JAORMX** [comment]
The e2e test failed downloading the fedora iso. Might want to close and re-open this to re-kick that test.

**Comment by saschagrunert** [comment]
> The e2e test failed downloading the fedora iso. Might want to close and re-open this to re-kick that test.

Yes this happened the second time today, let me provide a fix.

**Review by JAORMX — APPROVED** [review]

**Comment by saschagrunert** [comment]
As expected, it now works with crun 0.17.

**Review by JAORMX — COMMENTED** [review]
/lgtm

**Pull request merged**
