### PR TITLE
Switch from github.com/hpcloud/tail to github.com/nxadm/tail

### LINKED ISSUE #516: Verify that audit.log rotation does not break the enricher
In some cases the enricher stopped working when the auditd logs got rotated on the local node. We should verify that this is still the case and fix the issue if it exists.

### PR DESCRIPTION
**Pull request by jhrozek**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
hpcloud/tail doesn't seem to be maintained anymore and there's quite a
few bugs accumulated, many have been fixed in the maintained fork:
    https://github.com/nxadm/tail/issues/6
including the one that prevents reading rotated audit logs. Let's switch
to the maintained version.

#### Which issue(s) this PR fixes:
Fixes #516

#### Does this PR have test?
N/A relies on existing tests

#### Special notes for your reviewer:
N/A

#### Does this PR introduce a user-facing change?

```release-note
NONE

```

### CODE REVIEW

**Comment by JAORMX** [comment]
Looks good. I'll tag this one it passes CI

**Review by JAORMX — APPROVED** [review]
/lgtm

**Review by saschagrunert — APPROVED** [review]
Thank you!

**Pull request merged**
