### PR TITLE
Switch to latest CRI-O master for e2e tests

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
To be able to write a test for multi-container recording, we need the
latest CRI-O running within the e2e test suite. This also enables the
usage of the latest crun release, which is now per default available
within the bundle.
#### Which issue(s) this PR fixes:

None
#### Does this PR have test?
None

#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
Looks like the test output has now changed and needs some rework.

**Comment by saschagrunert** [comment]
Depends on https://github.com/cri-o/cri-o/pull/4618 and https://github.com/cri-o/cri-o/pull/4610

**Comment by saschagrunert** [comment]
Ah I can follow-up with the CRI-O changes later on when writing the tests. PTAL

**Review by hasheddan — APPROVED** [review]
/lgtm

**Pull request merged**
