### PR TITLE
`spoc record --no-proc`: include all namespaces

### PR DESCRIPTION
**Pull request by mhils**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

This PR builds on #2296: Since we already filter by program name when running `spoc record`, we don't need to limit ourselves to a single mntns. This way we don't have to apply somewhat brittle heuristics to find the correct namespace. One result of this is that we can remove the `--sleep` in the test!

#### Which issue(s) this PR fixes:

None

#### Does this PR have test?

Yes.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by ccojocar — APPROVED** [review]

**Review by saschagrunert — APPROVED** [review]
/ok-to-test

**Comment by saschagrunert** [comment]
/lgtm cancel

```
internal/pkg/cli/recorder/recorder.go:307:3: type assertion must be checked (forcetypeassert)
		spec = profile.(*apparmorprofileapi.AppArmorProfile).Spec
```

**Review by ccojocar — APPROVED** [review]

**Pull request merged**
