### PR TITLE
Fix panic when AppArmor is enabled

### PR DESCRIPTION
**Pull request by pjbgf**
#### What type of PR is this?

/kind bug
/kind regression

#### What this PR does / why we need it:

Fixes the controller panicking when AppArmor is enabled. The error encountered is as follows:

```
E0728 20:07:01.722796       1 controller.go:326]  "msg"="Reconciler error" "error"="getting owner profile: the node status owner is of an unknown kind" "controller"="pods" "controllerGroup"="" "controllerKind"="Pod" "name"="flux-source-controller-kube-control-plane1" "namespace"="security-profiles-operator" "reconcileID"="d2e07430-1c45-4e97-a9aa-10a4cc01f7d5" "securityProfileNodeStatus"={"name":"flux-source-controller-kube-control-plane1","namespace":"security-profiles-operator"} 
I0728 20:07:01.722839       1 nodestatus.go:117] nodestatus "msg"="Reconciling node status" "namespace"="security-profiles-operator" "nodeStatus"="flux-source-controller-kube-worker2" 
E0728 20:07:01.722874       1 controller.go:326]  "msg"="Reconciler error" "error"="getting owner profile: the node status owner is of an unknown kind" "controller"="pods" "controllerGroup"="" "controllerKind"="Pod" "name"="flux-source-controller-kube-worker2" "namespace"="security-profiles-operator" "reconcileID"="f1fa409a-4559-47fa-b509-7edbf49ed1f1" "securityProfileNodeStatus"={"name":"flux-source-controller-kube-worker2","namespace":"security-profiles-operator"} 
I0728 20:07:01.722896       1 nodestatus.go:117] nodestatus "msg"="Reconciling node status" "namespace"="security-profiles-operator" "nodeStatus"="flux-source-controller-kube-worker1" 
E0728 20:07:01.722922       1 controller.go:326]  "msg"="Reconciler error" "error"="getting owner profile: the node status owner is of an unknown kind" "controller"="pods" "controllerGroup"="" "controllerKind"="Pod" "name"="flux-source-controller-kube-worker1" "namespace"="security-profiles-operator" "reconcileID"="1387f8d3-308a-4568-a1fb-ba4ccb4140df" "securityProfileNodeStatus"={"name":"flux-source-controller-kube-worker1","namespace":"security-profiles-operator"} 
I0728 20:07:01.723223       1 controller.go:117]  "msg"="Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference" "controller"="pods" "controllerGroup"="" "controllerKind"="Pod" "name"="spod" "namespace"="security-profiles-operator" "reconcileID"="16e930ef-891f-4b5e-8449-3930631585a8" "securityProfilesOperatorDaemon"={"name":"spod","namespace":"security-profiles-operator"} 
panic: 2022-07-28T16:07:01.725550677-04:00 runtime error: invalid memory address or nil pointer dereference2022-07-28T16:07:01.725595790-04:00  [recovered]2022-07-28T16:07:01.725640324-04:00 
	2022-07-28T16:07:01.725729681-04:00 panic: 2022-07-28T16:07:01.725774415-04:00 runtime error: invalid memory address or nil pointer dereference2022-07-28T16:07:01.725818968-04:00 
[signal 2022-07-28T16:07:01.725908154-04:00 SIGSEGV: segmentation violation2022-07-28T16:07:01.725952718-04:00  code=2022-07-28T16:07:01.725996871-04:00 0x12022-07-28T16:07:01.726040963-04:00  addr=2022-07-28T16:07:01.726085276-04:00 0x282022-07-28T16:07:01.726129538-04:00  pc=2022-07-28T16:07:01.726173771-04:00 0x16a8fd52022-07-28T16:07:01.726218154-04:00 ]

goroutine 2022-07-28T16:07:01.726351322-04:00 3432022-07-28T16:07:01.726395536-04:00  [2022-07-28T16:07:01.726439838-04:00 running2022-07-28T16:07:01.726484261-04:00 ]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func12022-07-28T16:07:01.726577165-04:00 (2022-07-28T16:07:01.726621879-04:00 )
	2022-07-28T16:07:01.726710254-04:00 sigs.k8s.io/controller-runtime@v0.12.1/pkg/internal/controller/controller.go2022-07-28T16:07:01.726754787-04:00 :2022-07-28T16:07:01.726798889-04:00 1182022-07-28T16:07:01.726843293-04:00  +2022-07-28T16:07:01.726887444-04:00 0x1f42022-07-28T16:07:01.726931958-04:00 
panic2022-07-28T16:07:01.727057984-04:00 (2022-07-28T16:07:01.727103588-04:00 {2022-07-28T16:07:01.727148633-04:00 0x19b94002022-07-28T16:07:01.727193117-04:00 , 2022-07-28T16:07:01.727237559-04:00 0x2c266902022-07-28T16:07:01.727282133-04:00 }2022-07-28T16:07:01.727326555-04:00 )
	2022-07-28T16:07:01.727414851-04:00 runtime/panic.go2022-07-28T16:07:01.727459133-04:00 :2022-07-28T16:07:01.727503136-04:00 8382022-07-28T16:07:01.727542660-04:00  +2022-07-28T16:07:01.727572325-04:00 0x2072022-07-28T16:07:01.727602101-04:00 
sigs.k8s.io/security-profiles-operator/internal/pkg/manager/spod.(*ReconcileSPOd).getConfiguredSPOd2022-07-28T16:07:01.727667813-04:00 (2022-07-28T16:07:01.727698371-04:00 0xc000510d902022-07-28T16:07:01.727728107-04:00 , 2022-07-28T16:07:01.727757923-04:00 0xc00055f4002022-07-28T16:07:01.727788058-04:00 , 2022-07-28T16:07:01.727817804-04:00 {2022-07-28T16:07:01.727847650-04:00 0xc0007680502022-07-28T16:07:01.727877415-04:00 , 2022-07-28T16:07:01.727907051-04:00 0x472022-07-28T16:07:01.727936777-04:00 }2022-07-28T16:07:01.727966492-04:00 , 2022-07-28T16:07:01.727996057-04:00 {2022-07-28T16:07:01.728025933-04:00 0xc0007f4b302022-07-28T16:07:01.728055649-04:00 , 2022-07-28T16:07:01.728085395-04:00 0x62022-07-28T16:07:01.728122493-04:00 }2022-07-28T16:07:01.728152580-04:00 , 2022-07-28T16:07:01.728182496-04:00 0x02022-07-28T16:07:01.728212552-04:00 )
	2022-07-28T16:07:01.728272033-04:00 sigs.k8s.io/security-profiles-operator/internal/pkg/manager/spod/spod_controller.go2022-07-28T16:07:01.728301769-04:00 :2022-07-28T16:07:01.728331354-04:00 5792022-07-28T16:07:01.728361100-04:00  +2022-07-28T16:07:01.728390805-04:00 0x19752022-07-28T16:07:01.728420531-04:00 
sigs.k8s.io/security-profiles-operator/internal/pkg/manager/spod.(*ReconcileSPOd).Reconcile2022-07-28T16:07:01.728482386-04:00 (2022-07-28T16:07:01.728512894-04:00 0xc000510d902022-07-28T16:07:01.728542949-04:00 , 2022-07-28T16:07:01.728572715-04:00 {2022-07-28T16:07:01.728602601-04:00 0xc0000628002022-07-28T16:07:01.728632267-04:00 ?2022-07-28T16:07:01.728662012-04:00 , 2022-07-28T16:07:01.728691708-04:00 0xc000770ed02022-07-28T16:07:01.728721483-04:00 ?2022-07-28T16:07:01.728751289-04:00 }2022-07-28T16:07:01.728781074-04:00 , 2022-07-28T16:07:01.728810710-04:00 {2022-07-28T16:07:01.728840746-04:00 {2022-07-28T16:07:01.728870622-04:00 {2022-07-28T16:07:01.728930765-04:00 0xc0004c4d402022-07-28T16:07:01.728963486-04:00 ?2022-07-28T16:07:01.728993582-04:00 , 2022-07-28T16:07:01.729023418-04:00 0x102022-07-28T16:07:01.729053173-04:00 ?2022-07-28T16:07:01.729083020-04:00 }2022-07-28T16:07:01.729112734-04:00 , 2022-07-28T16:07:01.729142360-04:00 {2022-07-28T16:07:01.729172266-04:00 0xc0006995f82022-07-28T16:07:01.729201901-04:00 ?2022-07-28T16:07:01.729231747-04:00 , 2022-07-28T16:07:01.729261603-04:00 0x40f3e72022-07-28T16:07:01.729291309-04:00 ?2022-07-28T16:07:01.729320984-04:00 }2022-07-28T16:07:01.729350729-04:00 }2022-07-28T16:07:01.729380505-04:00 }2022-07-28T16:07:01.729410361-04:00 )
	2022-07-28T16:07:01.729469381-04:00 sigs.k8s.io/security-profiles-operator/internal/pkg/manager/spod/spod_controller.go2022-07-28T16:07:01.729498837-04:00 :2022-07-28T16:07:01.729528441-04:00 1582022-07-28T16:07:01.729558217-04:00  +2022-07-28T16:07:01.729587843-04:00 0x4272022-07-28T16:07:01.729617619-04:00 
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile2022-07-28T16:07:01.729678692-04:00 (2022-07-28T16:07:01.729709150-04:00 0x1f3be682022-07-28T16:07:01.729738926-04:00 ?2022-07-28T16:07:01.729768680-04:00 , 2022-07-28T16:07:01.729798356-04:00 {2022-07-28T16:07:01.729828212-04:00 0x1f3bf102022-07-28T16:07:01.729857907-04:00 ?2022-07-28T16:07:01.729887793-04:00 , 2022-07-28T16:07:01.729917559-04:00 0xc000770ed02022-07-28T16:07:01.729947265-04:00 ?2022-07-28T16:07:01.729977060-04:00 }2022-07-28T16:07:01.730006786-04:00 , 2022-07-28T16:07:01.730036411-04:00 {2022-07-28T16:07:01.730066197-04:00 {2022-07-28T16:07:01.730095962-04:00 {2022-07-28T16:07:01.730125748-04:00 0xc0004c4d402022-07-28T16:07:01.730155364-04:00 ?2022-07-28T16:07:01.730185119-04:00 , 2022-07-28T16:07:01.730214955-04:00 0x1b3c1602022-07-28T16:07:01.730244610-04:00 ?2022-07-28T16:07:01.730274296-04:00 }2022-07-28T16:07:01.730304021-04:00 , 2022-07-28T16:07:01.730333657-04:00 {2022-07-28T16:07:01.730363473-04:00 0xc0006995f82022-07-28T16:07:01.730393127-04:00 ?2022-07-28T16:07:01.730429486-04:00 , 2022-07-28T16:07:01.730459672-04:00 0x404ad42022-07-28T16:07:01.730489749-04:00 ?2022-07-28T16:07:01.730519604-04:00 }2022-07-28T16:07:01.730549360-04:00 }2022-07-28T16:07:01.730579096-04:00 }2022-07-28T16:07:01.730608882-04:00 )
	2022-07-28T16:07:01.730668032-04:00 sigs.k8s.io/controller-runtime@v0.12.1/pkg/internal/controller/controller.go2022-07-28T16:07:01.730697627-04:00 :2022-07-28T16:07:01.730727212-04:00 1212022-07-28T16:07:01.730757088-04:00  +2022-07-28T16:07:01.730786694-04:00 0xc82022-07-28T16:07:01.730816419-04:00 
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler2022-07-28T16:07:01.730877894-04:00 (2022-07-28T16:07:01.730908301-04:00 0xc00052ea002022-07-28T16:07:01.730938377-04:00 , 2022-07-28T16:07:01.730976047-04:00 {2022-07-28T16:07:01.731007577-04:00 0x1f3be682022-07-28T16:07:01.731037793-04:00 , 2022-07-28T16:07:01.731067708-04:00 0xc0005ff7002022-07-28T16:07:01.731097585-04:00 }2022-07-28T16:07:01.731127270-04:00 , 2022-07-28T16:07:01.731156915-04:00 {2022-07-28T16:07:01.731186791-04:00 0x1a3c9c02022-07-28T16:07:01.731216477-04:00 ?2022-07-28T16:07:01.731246233-04:00 , 2022-07-28T16:07:01.731275968-04:00 0xc0004138c02022-07-28T16:07:01.731305523-04:00 ?2022-07-28T16:07:01.731335159-04:00 }2022-07-28T16:07:01.731364885-04:00 )
	2022-07-28T16:07:01.731423945-04:00 sigs.k8s.io/controller-runtime@v0.12.1/pkg/internal/controller/controller.go2022-07-28T16:07:01.731453510-04:00 :2022-07-28T16:07:01.731483055-04:00 3202022-07-28T16:07:01.731512821-04:00  +2022-07-28T16:07:01.731542326-04:00 0x33c2022-07-28T16:07:01.731572072-04:00 
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem2022-07-28T16:07:01.731633506-04:00 (2022-07-28T16:07:01.731663873-04:00 0xc00052ea002022-07-28T16:07:01.731693729-04:00 , 2022-07-28T16:07:01.731723484-04:00 {2022-07-28T16:07:01.731753340-04:00 0x1f3be682022-07-28T16:07:01.731783076-04:00 , 2022-07-28T16:07:01.731812881-04:00 0xc0005ff7002022-07-28T16:07:01.731842617-04:00 }2022-07-28T16:07:01.731872383-04:00 )
	2022-07-28T16:07:01.731931473-04:00 sigs.k8s.io/controller-runtime@v0.12.1/pkg/internal/controller/controller.go2022-07-28T16:07:01.731960958-04:00 :2022-07-28T16:07:01.731990734-04:00 2732022-07-28T16:07:01.732020580-04:00  +2022-07-28T16:07:01.732050215-04:00 0x1d92022-07-28T16:07:01.732079971-04:00 
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.22022-07-28T16:07:01.732141155-04:00 (2022-07-28T16:07:01.732170991-04:00 )
	2022-07-28T16:07:01.732230172-04:00 sigs.k8s.io/controller-runtime@v0.12.1/pkg/internal/controller/controller.go2022-07-28T16:07:01.732259626-04:00 :2022-07-28T16:07:01.732289092-04:00 2342022-07-28T16:07:01.732318777-04:00  +2022-07-28T16:07:01.732348323-04:00 0x852022-07-28T16:07:01.732377948-04:00 
created by 2022-07-28T16:07:01.732439293-04:00 sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func22022-07-28T16:07:01.732468968-04:00 
	2022-07-28T16:07:01.732529151-04:00 sigs.k8s.io/controller-runtime@v0.12.1/pkg/internal/controller/controller.go2022-07-28T16:07:01.732565098-04:00 :2022-07-28T16:07:01.732595093-04:00 2302022-07-28T16:07:01.732624960-04:00  +2022-07-28T16:07:01.732654675-04:00 0x3252022-07-28T16:07:01.732684410-04:00
```

Generally, SELinux is not meant to be enabled concurrently with AppArmor, therefore it is safe to assume that SELinuxOptions may not be set in such situation.

#### Which issue(s) this PR fixes:

Relates to https://github.com/kubernetes-sigs/security-profiles-operator/issues/718

#### Does this PR have test?

N/A

#### Special notes for your reviewer:

This PR suffered from scope creep, which led to increased documentation and improved reliability.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]

**Comment by keskad** [comment]
I can confirm I was impacted by this case, as a workaround I had to set `selinuxTypeTag: ""`

**Review by saschagrunert — APPROVED** [review]

**Review by saschagrunert — APPROVED** [review]

**Comment by pjbgf** [comment]
Made some small changes that seem to have fixed the majority of the issues.

**Pull request merged**
