### PR TITLE
Bump kustomize to v4.5.3

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
Update kustomize to the latest release.
#### Which issue(s) this PR fixes:

None
#### Does this PR have test?
None

#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by JAORMX — APPROVED** [review]

**Comment by saschagrunert** [comment]
@k8s-ci-robot ?

/test pull-security-profiles-operator-test-e2e

**Pull request merged**
