### PR TITLE
doc: Restricted PSS/restricted SCC allows the use of custom seccomp profiles, but not SELinux

### PR DESCRIPTION
**Pull request by jhrozek**
#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:
Our documentation suggested that even using a custom seccomp profile
requires the use of a more privileged SCC. This is not true, both the
restricted SCC and the restricted PSS allows the use of localhost/
seccomp profiles, but not custom SELinux policies.

#### Which issue(s) this PR fixes:
None

#### Does this PR have test?
N/A

#### Special notes for your reviewer:
N/A

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by jhrozek** [comment]
CC @sheriff-rh

**Review by saschagrunert — APPROVED** [review]
Changes LGTM, but

/hold

for https://github.com/kubernetes-sigs/security-profiles-operator/pull/1317

**Comment by jhrozek** [comment]
#1317 was merged so I'm unholding this PR
/hold cancel

**Review by saschagrunert — APPROVED** [review]

**Comment by saschagrunert** [comment]
Just a docs change, merging now.

**Pull request merged**
