### PR TITLE
images: use k8s-staging-test-infra/gcb-docker-gcloud

### PR DESCRIPTION
**Pull request by spiffxp**
Related:
- Part of: https://github.com/kubernetes/k8s.io/issues/1523

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
Thanks!
/ok-to-test

**Comment by saschagrunert** [comment]
The usual flake. 
/override pull-security-profiles-operator-verify

**Comment by spiffxp** [comment]
Followup PR: https://github.com/kubernetes-sigs/security-profiles-operator/pull/730

**Pull request merged**
