### PR TITLE
fix: remove the control-plane taint to allow calico controller to be scheduled

### PR DESCRIPTION
**Pull request by ccojocar**
Signed-off-by: Cosmin Cojocar <gcojocar@adobe.com>

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
Awesome, thank you!

**Review by JAORMX — APPROVED** [review]

**Comment by ccojocar** [comment]
It seems that two e2e tests failed after removing the taint. This reason is that they were never executed before because the list of nodes provided to the tests was always empty due to the taint. They should should run now and complete successfully.

**Review by jhrozek — APPROVED** [review]
Thank you very much for fixing the tests so quickly!
/lgtm

**Pull request merged**
