### PR TITLE
tests: Enable SELinux in tests

### PR DESCRIPTION
**Pull request by jhrozek**
#### What type of PR is this?
/kind bug
/kind failing-test

#### What this PR does / why we need it:
Since the recent change to create spod in the operator itself, the spod
resource has been created with selinux disabled, thus failing all the
tests.

Long-term we should probably auto-detect the platform capabilities, but
for now, let's just enable selinux if selinux-related tests are selected
and wait for the DS to roll out.

#### Which issue(s) this PR fixes:
None

#### Does this PR have test?
This PR fixes tests

#### Special notes for your reviewer:
N/A

#### Does this PR introduce a user-facing change?

```release-note
NONE

```

### CODE REVIEW

**Comment by jhrozek** [comment]
Huh?
```
I0315 10:05:46.318767   22869 suite_test.go:445]  "msg"="Enable selinux in SPOD"  
securityprofilesoperatordaemon.security-profiles-operator.x-k8s.io/spod patched
securityprofilesoperatordaemon.security-profiles-operator.x-k8s.io/spod condition met
error: timed out waiting for the condition on pods/spod-cglln
```
I guess it's time to look at the tests locally...

**Comment by jhrozek** [comment]
Oh darn, it might be waiting on the condition of one of the pods that's shutting down, lol. Let me fix up the patch.

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Comment by JAORMX** [comment]
```
securityprofilesoperatordaemon.security-profiles-operator.x-k8s.io/spod patched
securityprofilesoperatordaemon.security-profiles-operator.x-k8s.io/spod condition met
Error from server (NotFound): daemonsets.apps "spod" not found
```

**Comment by jhrozek** [comment]
yeah, let me fix that up
/hold

**Comment by jhrozek** [comment]
I'm a dumbass and didn't include the NS in the kubectl call. 
```
diff --git a/test/suite_test.go b/test/suite_test.go
index a5464b7..25f3f1e 100644
--- a/test/suite_test.go
+++ b/test/suite_test.go
@@ -462,7 +462,7 @@ func (e *e2e) enableSelinuxInSpod() {
                time.Sleep(defaultWaitTime)
                e.waitInOperatorNSFor("condition=ready", "spod", "spod")

-               e.kubectl("rollout", "status", "ds", "spod", "--timeout", defaultSelinuxOpTimeout)
+               e.kubectlOperatorNS("rollout", "status", "ds", "spod", "--timeout", defaultSelinuxOpTimeout)
        }
 }
@JAORMX @saschagrunert PTAL again, this time the local vagrant e2e test worked for me, previously I was testing with an OCP cluster, I guess that's why I didn't see the issue.
```

**Comment by jhrozek** [comment]
/retest
this failure is unrelated and would be addressed with the conditions

**Pull request merged**
