### PR TITLE
OCPBUGS-25373: Revert "Use `metav1.Condition` type directly"

### PR DESCRIPTION
**Pull request by yuumasato**
#### What type of PR is this?

/kind bug
/kind failing-test
/kind regression

#### What this PR does / why we need it:
- This reverts commit bbec98ac86c2b575632d8f6c0a0cf54d0166fd37.
  - Message is required on https://pkg.go.dev/k8s.io/apimachinery/pkg/apis/meta/v1#Condition

#### Does this PR have test?
N/A

#### Special notes for your reviewer:
- Checking how CI's `make bundle` works on this change.
```release-note
Fixed upgrade issue introduced in v0.8.1.
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]

**Comment by BhargaviGudi** [comment]
Security-profile-operator regression test run passed with 4.14.6 + security-profile-operator from #2023 code

**Pull request merged**
