### PR TITLE
Switch to go1.16 images for GitHub actions

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
This switched the GitHub actions workflows to use golang 1.16. The prow
jobs will be updated in test-infra.
#### Which issue(s) this PR fixes:

None
#### Does this PR have test?
None

#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
Ref https://github.com/kubernetes/test-infra/pull/20878

**Comment by JAORMX** [comment]
@saschagrunert should we still have some coverage of go 1.15? at least in the test and build GH actions? Or do you think that's not worth it?

**Comment by saschagrunert** [comment]
> @saschagrunert should we still have some coverage of go 1.15? at least in the test and build GH actions? Or do you think that's not worth it?

I read the changelog and think we're fine to update to 1.16. I did not see anything specific which seems to be worth testing with the older version. :innocent:

**Comment by saschagrunert** [comment]
> /lgtm

Had to update go.mod/sum, this avoids breaking the CI when the test-infra PR merges. PTAL again.

**Pull request merged**
